АЛХАМУУД
1. Шинээр дата татаад шууд датабазад хадгалах, ингэснээр ID үүснэ
2. RESISTANCE and SUPPORT тодорхойлж датабаз руу ID-аар нь шүүд хадгална.

In [1]:
from utils.get_data import fetchCryptoData
import os
import time
import sys
from tabulate import tabulate
import ipywidgets as widgets
from IPython.display import display

In [2]:
from utils.get_data import fetchCryptoData
import os
import time
import sys
from tabulate import tabulate

symbol = 'ETHUSDT'
timePeriod = '1h'
lookback = 90000000
df = fetchCryptoData(symbol, timePeriod, lookback)
df.tail(2)

                   time     open     high      low    close       volume
998 2025-03-11 13:00:00  1894.91  1962.98  1867.00  1903.31  132070.3869
999 2025-03-11 14:00:00  1903.31  1912.63  1868.38  1881.08   66207.0103

In [3]:
# lookback tohiruulah widget
global lookback_slider, timePeriod
lookback_slider = widgets.IntSlider(
    value=200,
    min=10,
    max=900,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

lookback_input = widgets.BoundedIntText(
    value=200,
    min=10,
    max=900,
    step=1,
    description='Lookback:',
    disabled=False
)

# Link the slider and input field
widgets.jslink((lookback_slider, 'value'), (lookback_input, 'value'))

symbol = 'ETHUSDT'

# timePeriod tohiruulah widget
timePeriod = widgets.Dropdown(
    options=['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w'],
    value='1h',
    description='Time Period:',
    disabled=False,
)

def update_data(symbol, timePeriod, lookback):
    global df  # Declare df as global to update it
    df = fetchCryptoData(symbol, timePeriod, lookback)
    display(df.head())

widgets.interact(update_data, symbol=widgets.fixed(symbol), timePeriod=timePeriod, lookback=lookback_slider)

# display(lookback_slider, lookback_input)
# display(timePeriod)
# display

interactive(children=(Dropdown(description='Time Period:', index=4, options=('1m', '5m', '15m', '30m', '1h', '…

In [4]:
df

                   time     open     high      low    close       volume
0   2025-03-03 07:00:00  2372.68  2391.46  2352.79  2387.01   29191.7926
1   2025-03-03 08:00:00  2387.01  2388.11  2332.08  2345.41   31086.0888
2   2025-03-03 09:00:00  2345.41  2356.69  2322.01  2347.51   35838.1588
3   2025-03-03 10:00:00  2347.50  2366.29  2340.79  2359.19   22084.3278
4   2025-03-03 11:00:00  2359.18  2363.89  2344.40  2356.16   17653.0192
..                  ...      ...      ...      ...      ...          ...
195 2025-03-11 10:00:00  1917.29  1928.84  1910.69  1921.72   20313.2610
196 2025-03-11 11:00:00  1921.71  1926.00  1906.05  1914.12   29574.7304
197 2025-03-11 12:00:00  1914.12  1915.58  1887.01  1894.90   46506.6862
198 2025-03-11 13:00:00  1894.91  1962.98  1867.00  1903.31  132070.3869
199 2025-03-11 14:00:00  1903.31  1912.63  1868.38  1881.81   66212.6651

[200 rows x 6 columns]

In [5]:
lookback_slider.value

200

In [6]:
from utils.apply_technicals import apply_technicals
from utils.candle_patterns import detect_engulfing_pattern
from utils.price_channels import find_extremum
from utils.price_channels import support_resistance_range
from utils.trade_analyze import trade_analyze
from utils.boilinger_band import boilinger_band_check
from utils.save2mysql import create_database_if_not_exists
from utils.save2mysql import update_db
import pandas as pd
import numpy as np

# Create a list to collect processed rows
analyzed_df = pd.DataFrame(columns=['time', 'open', 'high', 'low', 'close', 'volume','support', 'resistance','macd','macd_signal','macd_hist','rsi','stochastic-K','stochastic-D','ema','bb_middle','bb_std','bb_upper','bb_lower','bb_trend','bb_signal','near_support','near_resistance','engulfing','reversal','doji','macd_trade','rsi_trade','stochastic_trade','channel_trade','near_bb_support','near_bb_resistance', 'trade'])
# Add the necessary columns if they do not exist
if 'support' not in df.columns:
    df['support'] = np.nan
if 'resistance' not in df.columns:
    df['resistance'] = np.nan
if 'macd' not in df.columns:
    df['macd'] = np.nan
if 'macd_signal' not in df.columns:
    df['macd_signal'] = np.nan
if 'macd_hist' not in df.columns:
    df['macd_hist'] = np.nan
if 'rsi' not in df.columns:
    df['rsi'] = np.nan
if 'stochastic-K' not in df.columns:
    df['stochastic-K'] = np.nan
if 'stochastic-D' not in df.columns:
    df['stochastic-D'] = np.nan
if 'ema' not in df.columns:
    df['ema'] = np.nan
if 'bb_middle' not in df.columns:
    df['bb_middle'] = np.nan
if 'bb_std' not in df.columns:
    df['bb_std'] = np.nan
if 'bb_upper' not in df.columns:
    df['bb_upper'] = np.nan
if 'bb_lower' not in df.columns:
    df['bb_lower'] = np.nan
if 'bb_trend' not in df.columns:
    df['bb_trend'] = np.nan
if 'bb_signal' not in df.columns:
    df['bb_signal'] = np.nan
if 'near_support' not in df.columns:
    df['near_support'] = np.nan
if 'near_resistance' not in df.columns:
    df['near_resistance'] = np.nan
if 'engulfing' not in df.columns:
    df['engulfing'] = 'no'
if 'reversal' not in df.columns:
    df['reversal'] = 'no'
if 'doji' not in df.columns:
    df['doji'] = 'no'
if 'macd_trade' not in df.columns:
    df['macd_trade'] = 'wait'
if 'rsi_trade' not in df.columns:
    df['rsi_trade'] = 'wait'
if 'stochastic_trade' not in df.columns:
    df['stochastic_trade'] = 'wait'
if 'channel_trade' not in df.columns:
    df['channel_trade'] = 'wait'
if 'near_bb_support' not in df.columns:
    df['near_bb_support'] = np.nan
if 'near_bb_resistance' not in df.columns:
    df['near_bb_resistance'] = np.nan
if 'trade' not in df.columns:
    df['trade'] = 'wait'
# === create database if not exists ===
create_database_if_not_exists()
print("Database created")
for index, row in df.iterrows():
    # for index, row in df.iterrows(): нь historical data-г нэг нэгээр авч байгаа simulation
    analyzed_df = df.iloc[0:index+1].copy()

    if len(analyzed_df) > 4: # call support_resistance_range after find_extremum
        # analyzed_df = support_resistance_range(analyzed_df, 10)
        analyzed_df = detect_engulfing_pattern(analyzed_df)
    if len(analyzed_df) > 20:
        analyzed_df = apply_technicals(analyzed_df)
        analyzed_df = boilinger_band_check(analyzed_df,20, 2, 10)
        # print(tabulate(analyzed_df[['time', 'engulfing','macd_hist', 'macd_trade', 'rsi_trade', 'stochastic_trade', 'channel_trade', 'bb_trend', 'bb_signal']].tail(4), headers='keys', tablefmt='psql', floatfmt='.4f'))
    update_db(row)
    latest_row = analyzed_df.iloc[-1]
    update_db(latest_row)
print("Analysis completed")
print(analyzed_df.tail(10))

Database created
Data updated for time: 2025-03-03 07:00:00
Data updated for time: 2025-03-03 07:00:00
Data updated for time: 2025-03-03 08:00:00
Data updated for time: 2025-03-03 08:00:00
Data updated for time: 2025-03-03 09:00:00
Data updated for time: 2025-03-03 09:00:00
Data updated for time: 2025-03-03 10:00:00
Data updated for time: 2025-03-03 10:00:00
Data updated for time: 2025-03-03 11:00:00
Data updated for time: 2025-03-03 11:00:00
Data updated for time: 2025-03-03 12:00:00
Data updated for time: 2025-03-03 12:00:00
Data updated for time: 2025-03-03 13:00:00
Data updated for time: 2025-03-03 13:00:00
Data updated for time: 2025-03-03 14:00:00
Data updated for time: 2025-03-03 14:00:00
Data updated for time: 2025-03-03 15:00:00
Data updated for time: 2025-03-03 15:00:00
Data updated for time: 2025-03-03 16:00:00
Data updated for time: 2025-03-03 16:00:00
Data updated for time: 2025-03-03 17:00:00
Data updated for time: 2025-03-03 17:00:00
Data updated for time: 2025-03-03 18:00:00
Data updated for time: 2025-03-03 18:00:00
Data updated for time: 2025-03-03 19:00:00
Data updated for time: 2025-03-03 19:00:00
Data updated for time: 2025-03-03 20:00:00
Data updated for time: 2025-03-03 20:00:00
Data updated for time: 2025-03-03 21:00:00
Data updated for time: 2025-03-03 21:00:00
Data updated for time: 2025-03-03 22:00:00
Data updated for time: 2025-03-03 22:00:00
Data updated for time: 2025-03-03 23:00:00
Data updated for time: 2025-03-03 23:00:00
Data updated for time: 2025-03-04 00:00:00
Data updated for time: 2025-03-04 00:00:00
Data updated for time: 2025-03-04 01:00:00
Data updated for time: 2025-03-04 01:00:00
Data updated for time: 2025-03-04 02:00:00
Data updated for time: 2025-03-04 02:00:00
Data updated for time: 2025-03-04 03:00:00
Data updated for time: 2025-03-04 03:00:00
Data updated for time: 2025-03-04 04:00:00
Data updated for time: 2025-03-04 04:00:00
Data updated for time: 2025-03-04 05:00:00
Data updated for time: 2025-03-04 05:00:00
Data updated for time: 2025-03-04 06:00:00
Data updated for time: 2025-03-04 06:00:00
Data updated for time: 2025-03-04 07:00:00
Data updated for time: 2025-03-04 07:00:00
Data updated for time: 2025-03-04 08:00:00
Data updated for time: 2025-03-04 08:00:00
Data updated for time: 2025-03-04 09:00:00
Data updated for time: 2025-03-04 09:00:00
Data updated for time: 2025-03-04 10:00:00
Data updated for time: 2025-03-04 10:00:00
Data updated for time: 2025-03-04 11:00:00
Data updated for time: 2025-03-04 11:00:00
Data updated for time: 2025-03-04 12:00:00
Data updated for time: 2025-03-04 12:00:00
Data updated for time: 2025-03-04 13:00:00
Data updated for time: 2025-03-04 13:00:00
Data updated for time: 2025-03-04 14:00:00
Data updated for time: 2025-03-04 14:00:00
Data updated for time: 2025-03-04 15:00:00
Data updated for time: 2025-03-04 15:00:00
Data updated for time: 2025-03-04 16:00:00
Data updated for time: 2025-03-04 16:00:00
Data updated for time: 2025-03-04 17:00:00
Data updated for time: 2025-03-04 17:00:00
Data updated for time: 2025-03-04 18:00:00
Data updated for time: 2025-03-04 18:00:00
Data updated for time: 2025-03-04 19:00:00
Data updated for time: 2025-03-04 19:00:00
Data updated for time: 2025-03-04 20:00:00
Data updated for time: 2025-03-04 20:00:00
Data updated for time: 2025-03-04 21:00:00
Data updated for time: 2025-03-04 21:00:00
Data updated for time: 2025-03-04 22:00:00
Data updated for time: 2025-03-04 22:00:00
Data updated for time: 2025-03-04 23:00:00
Data updated for time: 2025-03-04 23:00:00
Data updated for time: 2025-03-05 00:00:00
Data updated for time: 2025-03-05 00:00:00
Data updated for time: 2025-03-05 01:00:00
Data updated for time: 2025-03-05 01:00:00
Data updated for time: 2025-03-05 02:00:00
Data updated for time: 2025-03-05 02:00:00
Data updated for time: 2025-03-05 03:00:00
Data updated for time: 2025-03-05 03:00:00
Data updated for time: 2025-03-05 04:00:00
Data updated for time: 2025-03-05 04:00:00
Data updated for time: 2025-03-05 05:00:00
Data updated for time: 2025-03-05 05:00:00
Data updated for time: 2025-03-05 06:00:00
Data updated for time: 2025-03-05 06:00:00
Data updated for time: 2025-03-05 07:00:00
Data updated for time: 2025-03-05 07:00:00
Data updated for time: 2025-03-05 08:00:00
Data updated for time: 2025-03-05 08:00:00
Data updated for time: 2025-03-05 09:00:00
Data updated for time: 2025-03-05 09:00:00
Data updated for time: 2025-03-05 10:00:00
Data updated for time: 2025-03-05 10:00:00
Data updated for time: 2025-03-05 11:00:00
Data updated for time: 2025-03-05 11:00:00
Data updated for time: 2025-03-05 12:00:00
Data updated for time: 2025-03-05 12:00:00
Data updated for time: 2025-03-05 13:00:00
Data updated for time: 2025-03-05 13:00:00
Data updated for time: 2025-03-05 14:00:00
Data updated for time: 2025-03-05 14:00:00
Data updated for time: 2025-03-05 15:00:00
Data updated for time: 2025-03-05 15:00:00
Data updated for time: 2025-03-05 16:00:00
Data updated for time: 2025-03-05 16:00:00
Data updated for time: 2025-03-05 17:00:00
Data updated for time: 2025-03-05 17:00:00
Data updated for time: 2025-03-05 18:00:00
Data updated for time: 2025-03-05 18:00:00
Data updated for time: 2025-03-05 19:00:00
Data updated for time: 2025-03-05 19:00:00
Data updated for time: 2025-03-05 20:00:00
Data updated for time: 2025-03-05 20:00:00
Data updated for time: 2025-03-05 21:00:00
Data updated for time: 2025-03-05 21:00:00
Data updated for time: 2025-03-05 22:00:00
Data updated for time: 2025-03-05 22:00:00
Data updated for time: 2025-03-05 23:00:00
Data updated for time: 2025-03-05 23:00:00
Data updated for time: 2025-03-06 00:00:00
Data updated for time: 2025-03-06 00:00:00
Data updated for time: 2025-03-06 01:00:00
Data updated for time: 2025-03-06 01:00:00
Data updated for time: 2025-03-06 02:00:00
Data updated for time: 2025-03-06 02:00:00
Data updated for time: 2025-03-06 03:00:00
Data updated for time: 2025-03-06 03:00:00
Data updated for time: 2025-03-06 04:00:00
Data updated for time: 2025-03-06 04:00:00
Data updated for time: 2025-03-06 05:00:00
Data updated for time: 2025-03-06 05:00:00
Data updated for time: 2025-03-06 06:00:00
Data updated for time: 2025-03-06 06:00:00
Data updated for time: 2025-03-06 07:00:00
Data updated for time: 2025-03-06 07:00:00
Data updated for time: 2025-03-06 08:00:00
Data updated for time: 2025-03-06 08:00:00
Data updated for time: 2025-03-06 09:00:00
Data updated for time: 2025-03-06 09:00:00
Data updated for time: 2025-03-06 10:00:00
Data updated for time: 2025-03-06 10:00:00
Data updated for time: 2025-03-06 11:00:00
Data updated for time: 2025-03-06 11:00:00
Data updated for time: 2025-03-06 12:00:00
Data updated for time: 2025-03-06 12:00:00
Data updated for time: 2025-03-06 13:00:00
Data updated for time: 2025-03-06 13:00:00
Data updated for time: 2025-03-06 14:00:00
Data updated for time: 2025-03-06 14:00:00
Data updated for time: 2025-03-06 15:00:00
Data updated for time: 2025-03-06 15:00:00
Data updated for time: 2025-03-06 16:00:00
Data updated for time: 2025-03-06 16:00:00
Data updated for time: 2025-03-06 17:00:00
Data updated for time: 2025-03-06 17:00:00
Data updated for time: 2025-03-06 18:00:00
Data updated for time: 2025-03-06 18:00:00
Data updated for time: 2025-03-06 19:00:00
Data updated for time: 2025-03-06 19:00:00
Data updated for time: 2025-03-06 20:00:00
Data updated for time: 2025-03-06 20:00:00
Data updated for time: 2025-03-06 21:00:00
Data updated for time: 2025-03-06 21:00:00
Data updated for time: 2025-03-06 22:00:00
Data updated for time: 2025-03-06 22:00:00
Data updated for time: 2025-03-06 23:00:00
Data updated for time: 2025-03-06 23:00:00
Data updated for time: 2025-03-07 00:00:00
Data updated for time: 2025-03-07 00:00:00
Data updated for time: 2025-03-07 01:00:00
Data updated for time: 2025-03-07 01:00:00
Data updated for time: 2025-03-07 02:00:00
Data updated for time: 2025-03-07 02:00:00
Data updated for time: 2025-03-07 03:00:00
Data updated for time: 2025-03-07 03:00:00
Data updated for time: 2025-03-07 04:00:00
Data updated for time: 2025-03-07 04:00:00
Data updated for time: 2025-03-07 05:00:00
Data updated for time: 2025-03-07 05:00:00
Data updated for time: 2025-03-07 06:00:00
Data updated for time: 2025-03-07 06:00:00
Data updated for time: 2025-03-07 07:00:00
Data updated for time: 2025-03-07 07:00:00
Data updated for time: 2025-03-07 08:00:00
Data updated for time: 2025-03-07 08:00:00
Data updated for time: 2025-03-07 09:00:00
Data updated for time: 2025-03-07 09:00:00
Data updated for time: 2025-03-07 10:00:00
Data updated for time: 2025-03-07 10:00:00
Data updated for time: 2025-03-07 11:00:00
Data updated for time: 2025-03-07 11:00:00
Data updated for time: 2025-03-07 12:00:00
Data updated for time: 2025-03-07 12:00:00
Data updated for time: 2025-03-07 13:00:00
Data updated for time: 2025-03-07 13:00:00
Data updated for time: 2025-03-07 14:00:00
Data updated for time: 2025-03-07 14:00:00
Data updated for time: 2025-03-07 15:00:00
Data updated for time: 2025-03-07 15:00:00
Data updated for time: 2025-03-07 16:00:00
Data updated for time: 2025-03-07 16:00:00
Data updated for time: 2025-03-07 17:00:00
Data updated for time: 2025-03-07 17:00:00
Data updated for time: 2025-03-07 18:00:00
Data updated for time: 2025-03-07 18:00:00
Data updated for time: 2025-03-07 19:00:00
Data updated for time: 2025-03-07 19:00:00
Data updated for time: 2025-03-07 20:00:00
Data updated for time: 2025-03-07 20:00:00
Data updated for time: 2025-03-07 21:00:00
Data updated for time: 2025-03-07 21:00:00
Data updated for time: 2025-03-07 22:00:00
Data updated for time: 2025-03-07 22:00:00
Data updated for time: 2025-03-07 23:00:00
Data updated for time: 2025-03-07 23:00:00
Data updated for time: 2025-03-08 00:00:00
Data updated for time: 2025-03-08 00:00:00
Data updated for time: 2025-03-08 01:00:00
Data updated for time: 2025-03-08 01:00:00
Data updated for time: 2025-03-08 02:00:00
Data updated for time: 2025-03-08 02:00:00
Data updated for time: 2025-03-08 03:00:00
Data updated for time: 2025-03-08 03:00:00
Data updated for time: 2025-03-08 04:00:00
Data updated for time: 2025-03-08 04:00:00
Data updated for time: 2025-03-08 05:00:00
Data updated for time: 2025-03-08 05:00:00
Data updated for time: 2025-03-08 06:00:00
Data updated for time: 2025-03-08 06:00:00
Data updated for time: 2025-03-08 07:00:00
Data updated for time: 2025-03-08 07:00:00
Data updated for time: 2025-03-08 08:00:00
Data updated for time: 2025-03-08 08:00:00
Data updated for time: 2025-03-08 09:00:00
Data updated for time: 2025-03-08 09:00:00
Data updated for time: 2025-03-08 10:00:00
Data updated for time: 2025-03-08 10:00:00
Data updated for time: 2025-03-08 11:00:00
Data updated for time: 2025-03-08 11:00:00
Data updated for time: 2025-03-08 12:00:00
Data updated for time: 2025-03-08 12:00:00
Data updated for time: 2025-03-08 13:00:00
Data updated for time: 2025-03-08 13:00:00
Data updated for time: 2025-03-08 14:00:00
Data updated for time: 2025-03-08 14:00:00
Data updated for time: 2025-03-08 15:00:00
Data updated for time: 2025-03-08 15:00:00
Data updated for time: 2025-03-08 16:00:00
Data updated for time: 2025-03-08 16:00:00
Data updated for time: 2025-03-08 17:00:00
Data updated for time: 2025-03-08 17:00:00
Data updated for time: 2025-03-08 18:00:00
Data updated for time: 2025-03-08 18:00:00
Data updated for time: 2025-03-08 19:00:00
Data updated for time: 2025-03-08 19:00:00
Data updated for time: 2025-03-08 20:00:00
Data updated for time: 2025-03-08 20:00:00
Data updated for time: 2025-03-08 21:00:00
Data updated for time: 2025-03-08 21:00:00
Data updated for time: 2025-03-08 22:00:00
Data updated for time: 2025-03-08 22:00:00
Data updated for time: 2025-03-08 23:00:00
Data updated for time: 2025-03-08 23:00:00
Data updated for time: 2025-03-09 00:00:00
Data updated for time: 2025-03-09 00:00:00
Data updated for time: 2025-03-09 01:00:00
Data updated for time: 2025-03-09 01:00:00
Data updated for time: 2025-03-09 02:00:00
Data updated for time: 2025-03-09 02:00:00
Data updated for time: 2025-03-09 03:00:00
Data updated for time: 2025-03-09 03:00:00
Data updated for time: 2025-03-09 04:00:00
Data updated for time: 2025-03-09 04:00:00
Data updated for time: 2025-03-09 05:00:00
Data updated for time: 2025-03-09 05:00:00
Data updated for time: 2025-03-09 06:00:00
Data updated for time: 2025-03-09 06:00:00
Data saved for time: 2025-03-09 07:00:00
Data updated for time: 2025-03-09 07:00:00
Data saved for time: 2025-03-09 08:00:00
Data updated for time: 2025-03-09 08:00:00
Data saved for time: 2025-03-09 09:00:00
Data updated for time: 2025-03-09 09:00:00
Data saved for time: 2025-03-09 10:00:00
Data updated for time: 2025-03-09 10:00:00
Data saved for time: 2025-03-09 11:00:00
Data updated for time: 2025-03-09 11:00:00
Data saved for time: 2025-03-09 12:00:00
Data updated for time: 2025-03-09 12:00:00
Data saved for time: 2025-03-09 13:00:00
Data updated for time: 2025-03-09 13:00:00
Data saved for time: 2025-03-09 14:00:00
Data updated for time: 2025-03-09 14:00:00
Data saved for time: 2025-03-09 15:00:00
Data updated for time: 2025-03-09 15:00:00
Data saved for time: 2025-03-09 16:00:00
Data updated for time: 2025-03-09 16:00:00
Data saved for time: 2025-03-09 17:00:00
Data updated for time: 2025-03-09 17:00:00
Data saved for time: 2025-03-09 18:00:00
Data updated for time: 2025-03-09 18:00:00
Data saved for time: 2025-03-09 19:00:00
Data updated for time: 2025-03-09 19:00:00
Data saved for time: 2025-03-09 20:00:00
Data updated for time: 2025-03-09 20:00:00
Data saved for time: 2025-03-09 21:00:00
Data updated for time: 2025-03-09 21:00:00
Data saved for time: 2025-03-09 22:00:00
Data updated for time: 2025-03-09 22:00:00
Data saved for time: 2025-03-09 23:00:00
Data updated for time: 2025-03-09 23:00:00
Data saved for time: 2025-03-10 00:00:00
Data updated for time: 2025-03-10 00:00:00
Data saved for time: 2025-03-10 01:00:00
Data updated for time: 2025-03-10 01:00:00
Data saved for time: 2025-03-10 02:00:00
Data updated for time: 2025-03-10 02:00:00
Data saved for time: 2025-03-10 03:00:00
Data updated for time: 2025-03-10 03:00:00
Data saved for time: 2025-03-10 04:00:00
Data updated for time: 2025-03-10 04:00:00
Data saved for time: 2025-03-10 05:00:00
Data updated for time: 2025-03-10 05:00:00
Data saved for time: 2025-03-10 06:00:00
Data updated for time: 2025-03-10 06:00:00
Data saved for time: 2025-03-10 07:00:00
Data updated for time: 2025-03-10 07:00:00
Data saved for time: 2025-03-10 08:00:00
Data updated for time: 2025-03-10 08:00:00
Data saved for time: 2025-03-10 09:00:00
Data updated for time: 2025-03-10 09:00:00
Data saved for time: 2025-03-10 10:00:00
Data updated for time: 2025-03-10 10:00:00
Data saved for time: 2025-03-10 11:00:00
Data updated for time: 2025-03-10 11:00:00
Data saved for time: 2025-03-10 12:00:00
Data updated for time: 2025-03-10 12:00:00
Data saved for time: 2025-03-10 13:00:00
Data updated for time: 2025-03-10 13:00:00
Data saved for time: 2025-03-10 14:00:00
Data updated for time: 2025-03-10 14:00:00
Data saved for time: 2025-03-10 15:00:00
Data updated for time: 2025-03-10 15:00:00
Data saved for time: 2025-03-10 16:00:00
Data updated for time: 2025-03-10 16:00:00
Data saved for time: 2025-03-10 17:00:00
Data updated for time: 2025-03-10 17:00:00
Data saved for time: 2025-03-10 18:00:00
Data updated for time: 2025-03-10 18:00:00
Data saved for time: 2025-03-10 19:00:00
Data updated for time: 2025-03-10 19:00:00
Data saved for time: 2025-03-10 20:00:00
Data updated for time: 2025-03-10 20:00:00
Data saved for time: 2025-03-10 21:00:00
Data updated for time: 2025-03-10 21:00:00
Data saved for time: 2025-03-10 22:00:00
Data updated for time: 2025-03-10 22:00:00
Data saved for time: 2025-03-10 23:00:00
Data updated for time: 2025-03-10 23:00:00
Data saved for time: 2025-03-11 00:00:00
Data updated for time: 2025-03-11 00:00:00
Data saved for time: 2025-03-11 01:00:00
Data updated for time: 2025-03-11 01:00:00
Data saved for time: 2025-03-11 02:00:00
Data updated for time: 2025-03-11 02:00:00
Data saved for time: 2025-03-11 03:00:00
Data updated for time: 2025-03-11 03:00:00
Data saved for time: 2025-03-11 04:00:00
Data updated for time: 2025-03-11 04:00:00
Data saved for time: 2025-03-11 05:00:00
Data updated for time: 2025-03-11 05:00:00
Data saved for time: 2025-03-11 06:00:00
Data updated for time: 2025-03-11 06:00:00
Data saved for time: 2025-03-11 07:00:00
Data updated for time: 2025-03-11 07:00:00
Data saved for time: 2025-03-11 08:00:00
Data updated for time: 2025-03-11 08:00:00
Data saved for time: 2025-03-11 09:00:00
Data updated for time: 2025-03-11 09:00:00
Data saved for time: 2025-03-11 10:00:00
Data updated for time: 2025-03-11 10:00:00
Data saved for time: 2025-03-11 11:00:00
Data updated for time: 2025-03-11 11:00:00
Data saved for time: 2025-03-11 12:00:00
Data updated for time: 2025-03-11 12:00:00
Data saved for time: 2025-03-11 13:00:00
Data updated for time: 2025-03-11 13:00:00
Data saved for time: 2025-03-11 14:00:00
Data updated for time: 2025-03-11 14:00:00
Analysis completed
                   time     open     high      low    close       volume  \
190 2025-03-11 05:00:00  1869.06  1914.25  1866.62  1893.60   45804.7384
191 2025-03-11 06:00:00  1893.60  1905.60  1881.74  1884.83   21321.7011
192 2025-03-11 07:00:00  1884.82  1908.99  1882.98  1904.10   29352.4590
193 2025-03-11 08:00:00  1904.10  1920.00  1899.57  1907.50   30995.0341
194 2025-03-11 09:00:00  1907.50  1929.68  1906.18  1917.29   40984.6965
195 2025-03-11 10:00:00  1917.29  1928.84  1910.69  1921.72   20313.2610
196 2025-03-11 11:00:00  1921.71  1926.00  1906.05  1914.12   29574.7304
197 2025-03-11 12:00:00  1914.12  1915.58  1887.01  1894.90   46506.6862
198 2025-03-11 13:00:00  1894.91  1962.98  1867.00  1903.31  132070.3869
199 2025-03-11 14:00:00  1903.31  1912.63  1868.38  1881.81   66212.6651

     support  resistance  macd  macd_signal  ...  engulfing  reversal  \
190      NaN         NaN   NaN          NaN  ...         no        no
191      NaN         NaN   NaN          NaN  ...         no        no
192      NaN         NaN   NaN          NaN  ...         no        no
193      NaN         NaN   NaN          NaN  ...         no        no
194      NaN         NaN   NaN          NaN  ...         no        no
195      NaN         NaN   NaN          NaN  ...         no        no
196      NaN         NaN   NaN          NaN  ...         no        no
197      NaN         NaN   NaN          NaN  ...         no        no
198      NaN         NaN   NaN          NaN  ...         no        no
199      NaN         NaN   NaN          NaN  ...         no        no

             doji  macd_trade  rsi_trade  stochastic_trade  channel_trade  \
190            no        wait       wait              wait           wait
191            no        wait       wait              wait           wait
192            no        wait       wait              wait           wait
193            no        wait       wait              wait           wait
194            no        wait       wait              wait           wait
195            no        wait       wait              wait           wait
196            no        wait       wait              wait           wait
197            no        wait       wait              wait           wait
198  bullish_doji        wait       wait              wait           wait
199            no        wait       wait              wait           wait

     near_bb_support  near_bb_resistance trade
190              NaN                 NaN  wait
191              NaN                 NaN  wait
192              NaN                 NaN  wait
193              NaN                 NaN  wait
194              NaN                 NaN  wait
195              NaN                 NaN  wait
196              NaN                 NaN  wait
197              NaN                 NaN  wait
198              NaN                 NaN  wait

In [70]:
lookback_slider.value

200

In [7]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import mplfinance as mpf
import ta
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from datetime import datetime

# Date selection widgets
from_date = widgets.DatePicker(
    description='From',
    disabled=False
)
to_date = widgets.DatePicker(
    description='To',
    disabled=False
)

# Window size widget
window_size_input = widgets.IntText(
    value=200,
    description='Window Size:',
    disabled=False
)

# Submit button
submit_button = widgets.Button(
    description='Submit',
    disabled=False,
    button_style='',
    tooltip='Click to submit',
    icon='check'
)

# Display the widgets
display(from_date, to_date, window_size_input, submit_button)

# Database credentials
db_config = {
    'host': 'localhost',
    'user': 'root',
    'password': 'Tamir4578',
    'database': 'portalblog_dev'
}

table_name = 'analyzed_data'
timestamp_col = 'time'
open_col = 'open'
high_col = 'high'
low_col = 'low'
close_col = 'close'

# Create database connection string
db_connection_str = 'mysql+pymysql://{user}:{password}@{host}/{database}'.format(**db_config)
db_connection = create_engine(db_connection_str)

def fetch_data_from_db(window_size=200, start_date=None, end_date=None):
    query = f'SELECT * FROM (SELECT * FROM {table_name} ORDER BY {timestamp_col} DESC LIMIT {window_size}) AS recent_data'
    if start_date and end_date:
        query = f'SELECT * FROM (SELECT * FROM {table_name} WHERE {timestamp_col} BETWEEN "{start_date}" AND "{end_date}" ORDER BY {timestamp_col} DESC LIMIT {window_size}) AS recent_data'
    query += f' ORDER BY {timestamp_col} ASC'
    df = pd.read_sql(query, db_connection)
    # Convert the 'time' column to datetime
    df['time'] = pd.to_datetime(df['time'])

    # Set the 'time' column as the index
    df.set_index('time', inplace=True)
    return df

def on_submit_button_clicked(b):
    start_date = from_date.value.strftime('%Y-%m-%d') if from_date.value else None
    end_date = to_date.value.strftime('%Y-%m-%d') if to_date.value else None
    window_size = window_size_input.value
    global df
    df = fetch_data_from_db(window_size=window_size, start_date=start_date, end_date=end_date)
    # display(df.head())

submit_button.on_click(on_submit_button_clicked)

DatePicker(value=None, description='From', step=1)

DatePicker(value=None, description='To', step=1)

IntText(value=200, description='Window Size:')

Button(description='Submit', icon='check', style=ButtonStyle(), tooltip='Click to submit')

In [10]:
df.tail()

,id,open,high,low,close,volume,resistance,support,macd,macd_signal,...,stochastic_trade,channel_trade,bb_upper,bb_middle,bb_lower,bb_trend,bb_signal,near_bb_support,near_bb_resistance,trade
time,,,,,,,,,,,,,,,,,,,,,
2025-03-11 10:00:00,541,1917.29,1928.84,1910.69,1921.72,20313.3,None,None,None,None,...,wait,wait,1991.56,1890.86,1790.16,sideways,wait,NaN,NaN,wait
2025-03-11 11:00:00,542,1921.71,1926.00,1906.05,1914.12,29574.7,None,None,None,None,...,wait,wait,1967.81,1885.67,1803.53,sideways,wait,NaN,NaN,wait
2025-03-11 12:00:00,543,1914.12,1915.58,1887.01,1894.90,46506.7,None,None,None,None,...,wait,wait,1940.35,1880.15,1819.95,sideways,wait,NaN,NaN,wait
2025-03-11 13:00:00,544,1894.91,1962.98,1867.00,1903.31,132070.0,None,None,None,None,...,wait,wait,1938.11,1879.44,1820.78,sideways,wait,NaN,NaN,wait
2025-03-11 14:00:00,545,1903.31,1912.63,1868.38,1881.81,66212.7,None,None,None,None,...,wait,wait,1935.13,1882.26,1829.39,sideways,wait,NaN,NaN,wait

In [9]:
# Set the 'time' column as the index
df.set_index('time', inplace=True)

KeyError: "None of ['time'] are in the columns"

In [11]:
import plotly.graph_objects as go
def find_extremum(df, backcandles=500, candle_group=10):
    if df.index.name == 'time':
        df = df.reset_index().set_index('id')  # Reset index and set 'id' as the index
    candleid = len(df) - 1
    print("candle_id ", candleid)
    maxim = np.array([])
    minim = np.array([])
    xxmin = np.array([])
    xxmax = np.array([])

    for i in range(candleid - backcandles, candleid + 1, candle_group):
        minim = np.append(minim, df.low.iloc[i:i + candle_group].min())
        xxmin = np.append(xxmin, df.low.iloc[i:i + candle_group].idxmin())
    for i in range(candleid - backcandles, candleid + 1, candle_group):
        maxim = np.append(maxim, df.high.iloc[i:i + candle_group].max())
        xxmax = np.append(xxmax, df.high.iloc[i:i + candle_group].idxmax())
    slmin, intercmin = np.polyfit(xxmin, minim, 1)
    slmax, intercmax = np.polyfit(xxmax, maxim, 1)
    adjintercmin = df.low.iloc[candleid-backcandles:candleid].min() - slmin*df.low.iloc[candleid-backcandles:candleid].idxmin()
    adjintercmax = df.high.iloc[candleid-backcandles:candleid].max() - slmax*df.high.iloc[candleid-backcandles:candleid].idxmax()
    miny=slmin*xxmin + adjintercmin
    maxy=slmax*xxmax + adjintercmax
    return intercmin, intercmax,minim, maxim, xxmin, xxmax, slmin, slmax, adjintercmin, adjintercmax, miny, maxy

# ====== calculate support and resistance levels ======
intercmin, intercmax, minim, maxim, xxmin, xxmax, slmin, slmax, adjintercmin, adjintercmax, miny, maxy = find_extremum(df, 30, 5)
print("Slope max",slmax)
support_y=slmin*xxmin + adjintercmin
resistance_y=slmax*xxmax + adjintercmax
# dfpl = df[1:len(df)-1]
# intercmax = maxim.max() + intercmax
dfpl = df
fig = go.Figure(data=[go.Candlestick(x=dfpl.id,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])
fig.add_trace(go.Scatter(x=xxmin, y=slmin*xxmin + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmax, y=slmax*xxmax + adjintercmax, mode='lines', name='max slope'))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))

fig.show()

candle_id  199
Slope max -6.856336267605652

In [19]:
# ====== calculate support and resistance levels continiously ======
x_values = xxmin.astype(int)
for x in range(x_values[0], df.id.max() + 1):
    df.loc[df.id == x, 'support'] = slmin * x + adjintercmin
    df.loc[df.id == x, 'resistance'] = slmax * x + adjintercmax

In [20]:
df.tail(2)

,id,open,high,low,close,volume,resistance,support,macd,macd_signal,...,stochastic_trade,channel_trade,bb_upper,bb_middle,bb_lower,bb_trend,bb_signal,near_bb_support,near_bb_resistance,trade
time,,,,,,,,,,,,,,,,,,,,,
2025-03-11 13:00:00,544,1894.91,1962.98,1867.00,1903.31,132070.0,1960.422585,1699.986709,None,None,...,wait,wait,1938.11,1879.44,1820.78,sideways,wait,NaN,NaN,wait
2025-03-11 14:00:00,545,1903.31,1912.63,1868.38,1881.81,66212.7,1953.566248,1695.810302,None,None,...,wait,wait,1935.13,1882.26,1829.39,sideways,wait,NaN,NaN,wait

In [162]:
# Set the 'time' column as the index
df.set_index('time', inplace=True)

In [21]:
df.reset_index(inplace=True)
# df.set_index('id', inplace=True)

In [22]:
# Hadgalah
for index, row in df.iterrows():
    print(index)
    update_db(row)

0
Data updated for time: 2025-03-09 13:00:00
1
Data updated for time: 2025-03-09 14:00:00
2
Data updated for time: 2025-03-09 15:00:00
3
Data updated for time: 2025-03-09 16:00:00
4
Data updated for time: 2025-03-09 17:00:00
5
Data updated for time: 2025-03-09 18:00:00
6
Data updated for time: 2025-03-09 19:00:00
7
Data updated for time: 2025-03-09 20:00:00
8
Data updated for time: 2025-03-09 21:00:00
9
Data updated for time: 2025-03-09 22:00:00
10
Data updated for time: 2025-03-09 23:00:00
11
Data updated for time: 2025-03-10 00:00:00
12
Data updated for time: 2025-03-10 01:00:00
13
Data updated for time: 2025-03-10 02:00:00
14
Data updated for time: 2025-03-10 03:00:00
15
Data updated for time: 2025-03-10 04:00:00
16
Data updated for time: 2025-03-10 05:00:00
17
Data updated for time: 2025-03-10 06:00:00
18
Data updated for time: 2025-03-10 07:00:00
19
Data updated for time: 2025-03-10 08:00:00
20
Data updated for time: 2025-03-10 09:00:00
21
Data updated for time: 2025-03-10 10:00:00
22
Data updated for time: 2025-03-10 11:00:00
23
Data updated for time: 2025-03-10 12:00:00
24
Data updated for time: 2025-03-10 13:00:00
25
Data updated for time: 2025-03-10 14:00:00
26
Data updated for time: 2025-03-10 15:00:00
27
Data updated for time: 2025-03-10 16:00:00
28
Data updated for time: 2025-03-10 17:00:00
29
Data updated for time: 2025-03-10 18:00:00
30
Data updated for time: 2025-03-10 19:00:00
31
Data updated for time: 2025-03-10 20:00:00
32
Data updated for time: 2025-03-10 21:00:00
33
Data updated for time: 2025-03-10 22:00:00
34
Data updated for time: 2025-03-10 23:00:00
35
Data updated for time: 2025-03-11 00:00:00
36
Data updated for time: 2025-03-11 01:00:00
37
Data updated for time: 2025-03-11 02:00:00
38
Data updated for time: 2025-03-11 03:00:00
39
Data updated for time: 2025-03-11 04:00:00
40
Data updated for time: 2025-03-11 05:00:00
41
Data updated for time: 2025-03-11 06:00:00
42
Data updated for time: 2025-03-11 07:00:00
43
Data updated for time: 2025-03-11 08:00:00
44
Data updated for time: 2025-03-11 09:00:00
45
Data updated for time: 2025-03-11 10:00:00
46
Data updated for time: 2025-03-11 11:00:00
47
Data updated for time: 2025-03-11 12:00:00
48
Data updated for time: 2025-03-11 13:00:00
49
Data updated for time: 2025-03-11 14:00:00

SUPPORT & RESISTANCE hadgalsanaas hoish db-nees data tataj chart zurj shalgah heseg

In [23]:
# ==== db-nees data tataj chart zurah =====
df = fetch_data_from_db(window_size=200, start_date=None, end_date=None)

# Plot candlestick chart with support, resistance, and Bollinger Bands
fig = go.Figure(data=[go.Candlestick(x=df.index,
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'])])
fig.add_trace(go.Scatter(x=df.index, y=df['support'], mode='lines', name='Support', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['resistance'], mode='lines', name='Resistance', line=dict(color='red')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))

fig.update_layout(
    xaxis=dict(
        title="Time"
    ),
    yaxis=dict(
        title="Price"
    )
)

fig.show()

# Plot RSI chart separately
rsi_fig = go.Figure()
rsi_fig.add_trace(go.Scatter(x=df.index, y=df['rsi'], mode='lines', name='RSI', line=dict(color='purple')))

# Add RSI level lines
rsi_levels = [30, 50, 70]
for level in rsi_levels:
    rsi_fig.add_trace(go.Scatter(x=[df.index[0], df.index[-1]], y=[level, level], mode='lines', name=f'RSI {level}', line=dict(color='grey', dash='dash')))

# Update layout for RSI chart
rsi_fig.update_layout(
    yaxis=dict(
        title="RSI",
        range=[0, 100]
    ),
    xaxis=dict(
        title="Time"
    ),
    annotations=[
        dict(
            x=1.01,
            y=level,
            xref='paper',
            yref='y',
            text=f'RSI {level}',
            showarrow=False,
            font=dict(color='grey')
        ) for level in rsi_levels
    ]
)

rsi_fig.show()

In [ ]:
# ========= trade analyze =========
df = fetch_data_from_db(window_size=50, start_date=None, end_date=None)

# analyze with rsi and support and resistance and bollinger bands
price_range = 25
df['trade'] = 'wait'
df['trade'] = df.apply(lambda row: 'buy' if (row['close'] <= (row['support'] + 10) and row['close'] >= (row['support'] - 10) and pd.notnull(row['near_resistance']) and row['rsi'] < 35) else row['trade'], axis=1)
df['trade'] = df.apply(lambda row: 'sell' if (row['close'] <= (row['resistance'] + 10) and row['close'] >= (row['resistance'] - 10) and pd.notnull(row['near_bb_resistance']) and row['rsi'] > 65) else row['trade'], axis=1)
df['near_resistance'] = df.apply(lambda row: row['high'] if (abs(row['resistance'] - row['high'])) <= price_range and abs(row['bb_upper'] - row['high']) <= price_range else row['near_resistance'], axis=1)
df['near_resistance'] = df.apply(lambda row: row['high'] if (abs(row['resistance'] - row['high'])) <= price_range and abs(row['bb_upper'] - row['high']) <= price_range and pd.notnull(row['near_bb_resistance'] and row['rsi'] > 70) else row['near_resistance'], axis=1)
# df['near_support'] = df.apply(lambda row: row['low'] if (abs(row['support'] - row['low'])) <= price_range and abs(row['bb_lower'] - row['low']) <= price_range and pd.notnull(row['near_bb_support'] and row['rsi'] < 30) else row['near_support'], axis=1)
# Plot candlestick chart with support, resistance, and Bollinger Bands
fig = go.Figure(data=[go.Candlestick(x=df.index,
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'])])
fig.add_trace(go.Scatter(x=df.index, y=df['support'], mode='lines', name='Support', line=dict(color='green')))
fig.add_trace(go.Scatter(x=df.index, y=df['resistance'], mode='lines', name='Resistance', line=dict(color='red')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['near_support'], mode='markers', name='Near Support', marker=dict(symbol='star', color='red', size=10)))
fig.add_trace(go.Scatter(x=df.index, y=df['near_resistance'], mode='markers', name='Near Resistance', marker=dict(symbol='star',color='green', size=20)))
# fig.add_trace(go.Scatter(x=df.index, y=df['near_bb_support'], mode='markers', name='Near BB Support', marker=dict(symbol='star', color='blue', size=10)))
# fig.add_trace(go.Scatter(x=df.index, y=df['near_bb_resistance'], mode='markers', name='Near BB Resistance', marker=dict(color='red', size=10)))
fig.show()

In [164]:
df.reset_index(inplace=True)
# Hadgalah
for index, row in df.iterrows():
    print(index)
    update_db(row)

0
Data updated for time: 2025-03-07 05:00:00
1
Data updated for time: 2025-03-07 06:00:00
2
Data updated for time: 2025-03-07 07:00:00
3
Data updated for time: 2025-03-07 08:00:00
4
Data updated for time: 2025-03-07 09:00:00
5
Data updated for time: 2025-03-07 10:00:00
6
Data updated for time: 2025-03-07 11:00:00
7
Data updated for time: 2025-03-07 12:00:00
8
Data updated for time: 2025-03-07 13:00:00
9
Data updated for time: 2025-03-07 14:00:00
10
Data updated for time: 2025-03-07 15:00:00
11
Data updated for time: 2025-03-07 16:00:00
12
Data updated for time: 2025-03-07 17:00:00
13
Data updated for time: 2025-03-07 18:00:00
14
Data updated for time: 2025-03-07 19:00:00
15
Data updated for time: 2025-03-07 20:00:00
16
Data updated for time: 2025-03-07 21:00:00
17
Data updated for time: 2025-03-07 22:00:00
18
Data updated for time: 2025-03-07 23:00:00
19
Data updated for time: 2025-03-08 00:00:00
20
Data updated for time: 2025-03-08 01:00:00
21
Data updated for time: 2025-03-08 02:00:00
22
Data updated for time: 2025-03-08 03:00:00
23
Data updated for time: 2025-03-08 04:00:00
24
Data updated for time: 2025-03-08 05:00:00
25
Data updated for time: 2025-03-08 06:00:00
26
Data updated for time: 2025-03-08 07:00:00
27
Data updated for time: 2025-03-08 08:00:00
28
Data updated for time: 2025-03-08 09:00:00
29
Data updated for time: 2025-03-08 10:00:00
30
Data updated for time: 2025-03-08 11:00:00
31
Data updated for time: 2025-03-08 12:00:00
32
Data updated for time: 2025-03-08 13:00:00
33
Data updated for time: 2025-03-08 14:00:00
34
Data updated for time: 2025-03-08 15:00:00
35
Data updated for time: 2025-03-08 16:00:00
36
Data updated for time: 2025-03-08 17:00:00
37
Data updated for time: 2025-03-08 18:00:00
38
Data updated for time: 2025-03-08 19:00:00
39
Data updated for time: 2025-03-08 20:00:00
40
Data updated for time: 2025-03-08 21:00:00
41
Data updated for time: 2025-03-08 22:00:00
42
Data updated for time: 2025-03-08 23:00:00
43
Data updated for time: 2025-03-09 00:00:00
44
Data updated for time: 2025-03-09 01:00:00
45
Data updated for time: 2025-03-09 02:00:00
46
Data updated for time: 2025-03-09 03:00:00
47
Data updated for time: 2025-03-09 04:00:00
48
Data updated for time: 2025-03-09 05:00:00
49
Data updated for time: 2025-03-09 06:00:00

# Testing tactic for combination of BB and OSCI.

In [ ]:
df['osci_bb_buy'] = df.apply(lambda row: row['close'] if pd.notnull(row['near_bb_support']) and row['stochastic_trade'] == 'buy' else None, axis=1)
df['osci_bb_sell'] = df.apply(lambda row: row['close'] if pd.notnull(row['near_bb_resistance']) and row['stochastic_trade'] == 'sell' else None, axis=1)
osci_bb_buy_count = df['osci_bb_buy'].count()
osci_bb_sell_count = df['osci_bb_sell'].count()

print(f"osci_bb_buy count: {osci_bb_buy_count}")
print(f"osci_bb_sell count: {osci_bb_sell_count}")

# Define the Bollinger Bands
bbands = mpf.make_addplot(df[['bb_upper', 'bb_middle', 'bb_lower']])

# Define the buy and sell signals
buy_signals = mpf.make_addplot(df['osci_bb_buy'], type='scatter', markersize=100, marker='*', color='red')
sell_signals = mpf.make_addplot(df['osci_bb_sell'], type='scatter', markersize=100, marker='*', color='green')

# Plot the candlestick chart with Bollinger Bands and buy/sell signals
mpf.plot(df, type='candle', addplot=[bbands, buy_signals, sell_signals], volume=True, style='yahoo', figratio=(3, 1))

# Testing the combination of BB and RSI

In [6]:
# import numpy as np

# ============ calculate slope of bb_lower ============
def bb_lower_slope(df):
    # Select the last 4 points of data
    last_points = df['bb_lower'].tail(4)
    # Calculate the slope of the 'bb_lower' line
    x = np.arange(len(last_points))
    y = last_points.values
    slope, _ = np.polyfit(x, y, 1)
    # Convert slope to degrees
    slope_in_degrees = np.degrees(np.arctan(slope))
    return slope, slope_in_degrees

slope, degree = bb_lower_slope(df)
degree
slope

2.7379999999997615

Test with trend reversal detection by candlestick

SUPPORT and RESISTANCE

In [10]:
import pandas as pd
# df = pd.read_csv("EURUSD_Candlestick_4_Hour_ASK_05.05.2003-16.10.2021.csv")
# df.columns=['time', 'open', 'high', 'low', 'close', 'volume']
#Check if NA values are in data
df=df[df['volume']!=0]
df.reset_index(drop=True, inplace=True)
df.isna().sum()
df.head(10)

,id,open,high,low,close,volume,resistance,support,macd,macd_signal,...,bb_middle,bb_lower,bb_trend,bb_signal,near_bb_support,near_bb_resistance,ath,atl,osci_bb_buy,osci_bb_sell
0,492,3309.69,3335.44,3279.09,3289.41,46772.60,None,None,None,None,...,3278.17,3211.20,sideways,wait,NaN,3335.44,NaN,NaN,NaN,NaN
1,493,3289.42,3302.09,3265.11,3295.10,27063.40,None,None,None,None,...,3275.75,3215.56,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
2,494,3295.10,3349.17,3290.50,3313.85,34589.30,None,None,None,None,...,3275.43,3216.18,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
3,495,3313.85,3356.59,3307.81,3351.00,20466.40,None,None,None,None,...,3278.74,3210.55,sideways,wait,NaN,3356.59,NaN,NaN,NaN,NaN
4,496,3351.00,3368.00,3330.74,3345.76,21973.60,None,None,None,None,...,3280.10,3207.62,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
5,497,3345.75,3346.63,3318.00,3332.16,14995.40,None,None,None,None,...,3282.51,3206.37,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
6,498,3332.16,3339.49,3304.01,3314.39,11131.50,None,None,None,None,...,3286.88,3214.23,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
7,499,3314.39,3336.50,3302.03,3331.90,12215.40,None,None,None,None,...,3290.95,3217.74,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
8,500,3331.90,3347.12,3326.70,3333.74,8771.23,None,None,None,None,...,3294.74,3220.88,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN
9,501,3333.75,3334.89,3308.11,3327.54,15981.20,None,None,None,None,...,3297.98,3224.37,sideways,wait,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
backcandles= 50
wind = 5

candleid = 400

maxim = np.array([])
minim = np.array([])
xxmin = np.array([])
xxmax = np.array([])
for i in range(candleid-backcandles, candleid+1, wind):
    minim = np.append(minim, df.low.iloc[i:i+wind].min())
    xxmin = np.append(xxmin, df.low.iloc[i:i+wind].idxmin())
for i in range(candleid-backcandles, candleid+1, wind):
    maxim = np.append(maxim, df.high.loc[i:i+wind].max())
    xxmax = np.append(xxmax, df.high.iloc[i:i+wind].idxmax())
slmin, intercmin = np.polyfit(xxmin, minim,1)
slmax, intercmax = np.polyfit(xxmax, maxim,1)

dfpl = df[candleid-backcandles:candleid+backcandles]
fig = go.Figure(data=[go.Candlestick(x=dfpl.index,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])
fig.add_trace(go.Scatter(x=xxmin, y=slmin*xxmin + intercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmax, y=slmax*xxmax + intercmax, mode='lines', name='max slope'))

In [12]:
xxmin

array([351., 355., 364., 365., 371., 375., 384., 388., 392., 395., 400.])

In [13]:
minim

array([2709.2 , 2746.85, 2715.27, 2716.54, 2755.69, 2820.25, 2737.62,
       2672.03, 2655.28, 2687.  , 2668.03])

In [15]:
y=slmin*xxmin + intercmin
y

array([2751.75327056, 2746.22601642, 2733.78969461, 2732.40788108,
       2724.11699987, 2718.58974573, 2706.15342392, 2700.62616978,
       2695.09891564, 2690.95347503, 2684.04440736])

write function that save or update values of "y=slmin*xxmin + intercmin" into database by filtering 'ID'

In [19]:
def save_or_update_y_values(df, xxmin, y, table_name, db_connection):
    # Create a DataFrame with 'ID' and 'y' values
    y_df = pd.DataFrame({'ID': df.index[xxmin.astype(int)], 'y': y})

    # Iterate through the DataFrame and update or insert values into the database
    with db_connection.connect() as connection:
        for index, row in y_df.iterrows():
            query = f"""
            INSERT INTO {table_name} (ID, y)
            VALUES ({row['ID']}, {row['y']})
            ON DUPLICATE KEY UPDATE y = {row['y']}
            """
            connection.execute(query)

# Call the function
save_or_update_y_values(df, xxmin, y, 'analyzed_data', db_connection)

ObjectNotExecutableError: Not an executable object: '\n            INSERT INTO analyzed_data (ID, y)\n            VALUES (351.0, 2751.7532705626277)\n            ON DUPLICATE KEY UPDATE y = 2751.7532705626277\n            '

In [6]:
dfpl = df[candleid-wind-backcandles:candleid+backcandles]
import plotly.graph_objects as go
from datetime import datetime

fig = go.Figure(data=[go.Candlestick(x=dfpl.index,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])

#-------------------------------------------------------------------------
# Fitting intercepts to meet highest or lowest candle point in time slice
adjintercmin = df.low.loc[candleid-backcandles:candleid].min() - slmin*df.low.iloc[candleid-backcandles:candleid].idxmin()
adjintercmax = df.high.loc[candleid-backcandles:candleid].max() - slmax*df.high.iloc[candleid-backcandles:candleid].idxmax()
fig.add_trace(go.Scatter(x=xxmin, y=slmin*xxmin + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmax, y=slmax*xxmax + adjintercmax, mode='lines', name='max slope'))
fig.show()

In [7]:
dfpl = df[candleid-wind-backcandles:candleid+backcandles]
import plotly.graph_objects as go
from datetime import datetime

fig = go.Figure(data=[go.Candlestick(x=dfpl.index,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])

#-------------------------------------------------------------------------
# Fitting intercepts to wrap price candles
adjintercmax = (df.high.iloc[xxmax] - slmax*xxmax).max()
adjintercmin = (df.low.iloc[xxmin] - slmin*xxmin).min()
fig.add_trace(go.Scatter(x=xxmin, y=slmin*xxmin + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmax, y=slmax*xxmax + adjintercmax, mode='lines', name='max slope'))
fig.show()

backcandles time window more dynamic

In [14]:
import numpy as np
from matplotlib import pyplot
backcandles= 40 # 6*8
brange = 10 # backcandles//4 #should be less than backcandles
wind = 6

candleid = 420

optbackcandles= backcandles
sldiff = 500

for r1 in range(backcandles-brange, backcandles+brange):
    maxim = np.array([])
    minim = np.array([])
    xxmin = np.array([])
    xxmax = np.array([])
    for i in range(candleid-r1, candleid+1, wind):
        minim = np.append(minim, df.low.iloc[i:i+wind].min())
        xxmin = np.append(xxmin, df.low.iloc[i:i+wind].idxmin())
    for i in range(candleid-r1, candleid+1, wind):
        maxim = np.append(maxim, df.high.loc[i:i+wind].max())
        xxmax = np.append(xxmax, df.high.iloc[i:i+wind].idxmax())
    slmin, intercmin = np.polyfit(xxmin, minim,1)
    slmax, intercmax = np.polyfit(xxmax, maxim,1)

    if(abs(slmin-slmax)<sldiff):
        sldiff = abs(slmin-slmax)
        optbackcandles=r1
        slminopt = slmin
        slmaxopt = slmax
        intercminopt = intercmin
        intercmaxopt = intercmax
        maximopt = maxim.copy()
        minimopt = minim.copy()
        xxminopt = xxmin.copy()
        xxmaxopt = xxmax.copy()

        print(optbackcandles)
dfpl = df[candleid-wind-optbackcandles-backcandles:candleid+optbackcandles]
fig = go.Figure(data=[go.Candlestick(x=dfpl.index,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])

adjintercmax = (df.high.iloc[xxmaxopt] - slmaxopt*xxmaxopt).max()
adjintercmin = (df.low.iloc[xxminopt] - slminopt*xxminopt).min()
fig.add_trace(go.Scatter(x=xxminopt, y=slminopt*xxminopt + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmaxopt, y=slmaxopt*xxmaxopt + adjintercmax, mode='lines', name='max slope'))
fig.show()

30
37
38
43

In [11]:
import numpy as np
from matplotlib import pyplot
backcandles= 100
brange = 50 #should be less than backcandles
wind = 5

candleid = 480

optbackcandles= backcandles
sldiff = 100
sldist = 500
for r1 in range(backcandles-brange, backcandles+brange):
    maxim = np.array([])
    minim = np.array([])
    xxmin = np.array([])
    xxmax = np.array([])

    for i in range(candleid-r1, candleid+1, wind):
        minim = np.append(minim, df.low.iloc[i:i+wind].min())
        xxmin = np.append(xxmin, df.low.iloc[i:i+wind].idxmin())
    for i in range(candleid-r1, candleid+1, wind):
        maxim = np.append(maxim, df.high.loc[i:i+wind].max())
        xxmax = np.append(xxmax, df.high.iloc[i:i+wind].idxmax())
    slmin, intercmin = np.polyfit(xxmin, minim,1)
    slmax, intercmax = np.polyfit(xxmax, maxim,1)

    dist = (slmax*candleid + intercmax)-(slmin*candleid + intercmin)
    if(dist<sldist): #abs(slmin-slmax)<sldiff and
        #sldiff = abs(slmin-slmax)
        sldist = dist
        optbackcandles=r1
        slminopt = slmin
        slmaxopt = slmax
        intercminopt = intercmin
        intercmaxopt = intercmax
        maximopt = maxim.copy()
        minimopt = minim.copy()
        xxminopt = xxmin.copy()
        xxmaxopt = xxmax.copy()


print(optbackcandles)
dfpl = df[candleid-wind-optbackcandles-backcandles:candleid+optbackcandles]
fig = go.Figure(data=[go.Candlestick(x=dfpl.index,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])

adjintercmax = (df.high.iloc[xxmaxopt] - slmaxopt*xxmaxopt).max()
adjintercmin = (df.low.iloc[xxminopt] - slminopt*xxminopt).min()
fig.add_trace(go.Scatter(x=xxminopt, y=slminopt*xxminopt + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmaxopt, y=slmaxopt*xxmaxopt + adjintercmax, mode='lines', name='max slope'))
fig.show()

149