АЛХАМУУД
1. Шинээр дата татаад шууд датабазад хадгалах, ингэснээр ID үүснэ
2. RESISTANCE and SUPPORT тодорхойлж датабаз руу ID-аар нь шүүд хадгална.

In [1]:
from utils.get_data import fetchCryptoData
import os
import time
import sys
from tabulate import tabulate
import ipywidgets as widgets
from IPython.display import display

In [34]:
from utils.get_data import fetchCryptoData
import os
import time
import sys
from tabulate import tabulate

symbol = 'ETHUSDT'
timePeriod = '1h'
lookback = 90000000
df = fetchCryptoData(symbol, timePeriod, lookback)
df.tail(2)

                   time     open     high      low    close      volume
998 2025-03-12 10:00:00  1894.09  1902.00  1883.70  1900.33  29777.0658
999 2025-03-12 11:00:00  1900.34  1915.52  1900.34  1909.99   9314.0727

In [35]:
# lookback tohiruulah widget
global lookback_slider, timePeriod
lookback_slider = widgets.IntSlider(
    value=200,
    min=10,
    max=900,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

lookback_input = widgets.BoundedIntText(
    value=200,
    min=10,
    max=900,
    step=1,
    description='Lookback:',
    disabled=False
)

# Link the slider and input field
widgets.jslink((lookback_slider, 'value'), (lookback_input, 'value'))

symbol = 'ETHUSDT'

# timePeriod tohiruulah widget
timePeriod = widgets.Dropdown(
    options=['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w'],
    value='1h',
    description='Time Period:',
    disabled=False,
)

def update_data(symbol, timePeriod, lookback):
    global df  # Declare df as global to update it
    df = fetchCryptoData(symbol, timePeriod, lookback)
    display(df.head())

widgets.interact(update_data, symbol=widgets.fixed(symbol), timePeriod=timePeriod, lookback=lookback_slider)

# display(lookback_slider, lookback_input)
# display(timePeriod)
# display

interactive(children=(Dropdown(description='Time Period:', index=4, options=('1m', '5m', '15m', '30m', '1h', '…

In [36]:
df

                   time     open     high      low    close      volume
0   2025-03-04 04:00:00  2074.89  2093.69  2070.50  2082.04  23165.9219
1   2025-03-04 05:00:00  2082.04  2122.12  2078.49  2106.94  35770.8174
2   2025-03-04 06:00:00  2106.94  2111.87  2090.11  2097.66  17738.9892
3   2025-03-04 07:00:00  2097.66  2102.96  2068.34  2080.41  23430.0424
4   2025-03-04 08:00:00  2080.42  2106.05  2071.03  2099.03  25577.3598
..                  ...      ...      ...      ...      ...         ...
195 2025-03-12 07:00:00  1873.11  1916.66  1872.07  1911.26  52422.4788
196 2025-03-12 08:00:00  1911.26  1935.90  1871.11  1928.10  67585.9061
197 2025-03-12 09:00:00  1928.10  1960.00  1877.67  1894.10  97355.1544
198 2025-03-12 10:00:00  1894.09  1902.00  1883.70  1900.33  29777.0658
199 2025-03-12 11:00:00  1900.34  1915.52  1900.34  1909.99   9373.5371

[200 rows x 6 columns]

In [5]:
lookback_slider.value

200

In [37]:
from utils.apply_technicals import apply_technicals
from utils.candle_patterns import detect_engulfing_pattern
from utils.price_channels import find_extremum
from utils.price_channels import support_resistance_range
from utils.trade_analyze import trade_analyze
from utils.boilinger_band import boilinger_band_check
from utils.save2mysql import create_database_if_not_exists
from utils.save2mysql import update_db
import pandas as pd
import numpy as np

# Create a list to collect processed rows
analyzed_df = pd.DataFrame(columns=['time', 'open', 'high', 'low', 'close', 'volume','support', 'resistance','macd','macd_signal','macd_hist','rsi','stochastic-K','stochastic-D','ema','bb_middle','bb_std','bb_upper','bb_lower','bb_trend','bb_signal','near_support','near_resistance','engulfing','reversal','doji','macd_trade','rsi_trade','stochastic_trade','channel_trade','near_bb_support','near_bb_resistance', 'trade'])
# Add the necessary columns if they do not exist
if 'support' not in df.columns:
    df['support'] = np.nan
if 'resistance' not in df.columns:
    df['resistance'] = np.nan
if 'macd' not in df.columns:
    df['macd'] = np.nan
if 'macd_signal' not in df.columns:
    df['macd_signal'] = np.nan
if 'macd_hist' not in df.columns:
    df['macd_hist'] = np.nan
if 'rsi' not in df.columns:
    df['rsi'] = np.nan
if 'stochastic-K' not in df.columns:
    df['stochastic-K'] = np.nan
if 'stochastic-D' not in df.columns:
    df['stochastic-D'] = np.nan
if 'ema' not in df.columns:
    df['ema'] = np.nan
if 'bb_middle' not in df.columns:
    df['bb_middle'] = np.nan
if 'bb_std' not in df.columns:
    df['bb_std'] = np.nan
if 'bb_upper' not in df.columns:
    df['bb_upper'] = np.nan
if 'bb_lower' not in df.columns:
    df['bb_lower'] = np.nan
if 'bb_trend' not in df.columns:
    df['bb_trend'] = np.nan
if 'bb_signal' not in df.columns:
    df['bb_signal'] = np.nan
if 'near_support' not in df.columns:
    df['near_support'] = np.nan
if 'near_resistance' not in df.columns:
    df['near_resistance'] = np.nan
if 'engulfing' not in df.columns:
    df['engulfing'] = 'no'
if 'reversal' not in df.columns:
    df['reversal'] = 'no'
if 'doji' not in df.columns:
    df['doji'] = 'no'
if 'macd_trade' not in df.columns:
    df['macd_trade'] = 'wait'
if 'rsi_trade' not in df.columns:
    df['rsi_trade'] = 'wait'
if 'stochastic_trade' not in df.columns:
    df['stochastic_trade'] = 'wait'
if 'channel_trade' not in df.columns:
    df['channel_trade'] = 'wait'
if 'near_bb_support' not in df.columns:
    df['near_bb_support'] = np.nan
if 'near_bb_resistance' not in df.columns:
    df['near_bb_resistance'] = np.nan
if 'trade' not in df.columns:
    df['trade'] = 'wait'
# === create database if not exists ===
create_database_if_not_exists()
print("Database created")
for index, row in df.iterrows():
    # for index, row in df.iterrows(): нь historical data-г нэг нэгээр авч байгаа simulation
    analyzed_df = df.iloc[0:index+1].copy()

    if len(analyzed_df) > 4: # call support_resistance_range after find_extremum
        # analyzed_df = support_resistance_range(analyzed_df, 10)
        analyzed_df = detect_engulfing_pattern(analyzed_df)
    if len(analyzed_df) > 20:
        analyzed_df = apply_technicals(analyzed_df)
        analyzed_df = boilinger_band_check(analyzed_df,20, 2, 10)
        # print(tabulate(analyzed_df[['time', 'engulfing','macd_hist', 'macd_trade', 'rsi_trade', 'stochastic_trade', 'channel_trade', 'bb_trend', 'bb_signal']].tail(4), headers='keys', tablefmt='psql', floatfmt='.4f'))
    update_db(row)
    latest_row = analyzed_df.iloc[-1]
    update_db(latest_row)
print("Analysis completed")
print(analyzed_df.tail(10))

Database created
Data updated for time: 2025-03-04 04:00:00
Data updated for time: 2025-03-04 04:00:00
Data updated for time: 2025-03-04 05:00:00
Data updated for time: 2025-03-04 05:00:00
Data updated for time: 2025-03-04 06:00:00
Data updated for time: 2025-03-04 06:00:00
Data updated for time: 2025-03-04 07:00:00
Data updated for time: 2025-03-04 07:00:00
Data updated for time: 2025-03-04 08:00:00
Data updated for time: 2025-03-04 08:00:00
Data updated for time: 2025-03-04 09:00:00
Data updated for time: 2025-03-04 09:00:00
Data updated for time: 2025-03-04 10:00:00
Data updated for time: 2025-03-04 10:00:00
Data updated for time: 2025-03-04 11:00:00
Data updated for time: 2025-03-04 11:00:00
Data updated for time: 2025-03-04 12:00:00
Data updated for time: 2025-03-04 12:00:00
Data updated for time: 2025-03-04 13:00:00
Data updated for time: 2025-03-04 13:00:00
Data updated for time: 2025-03-04 14:00:00
Data updated for time: 2025-03-04 14:00:00
Data updated for time: 2025-03-04 15:00:00
Data updated for time: 2025-03-04 15:00:00
Data updated for time: 2025-03-04 16:00:00
Data updated for time: 2025-03-04 16:00:00
Data updated for time: 2025-03-04 17:00:00
Data updated for time: 2025-03-04 17:00:00
Data updated for time: 2025-03-04 18:00:00
Data updated for time: 2025-03-04 18:00:00
Data updated for time: 2025-03-04 19:00:00
Data updated for time: 2025-03-04 19:00:00
Data updated for time: 2025-03-04 20:00:00
Data updated for time: 2025-03-04 20:00:00
Data updated for time: 2025-03-04 21:00:00
Data updated for time: 2025-03-04 21:00:00
Data updated for time: 2025-03-04 22:00:00
Data updated for time: 2025-03-04 22:00:00
Data updated for time: 2025-03-04 23:00:00
Data updated for time: 2025-03-04 23:00:00
Data updated for time: 2025-03-05 00:00:00
Data updated for time: 2025-03-05 00:00:00
Data updated for time: 2025-03-05 01:00:00
Data updated for time: 2025-03-05 01:00:00
Data updated for time: 2025-03-05 02:00:00
Data updated for time: 2025-03-05 02:00:00
Data updated for time: 2025-03-05 03:00:00
Data updated for time: 2025-03-05 03:00:00
Data updated for time: 2025-03-05 04:00:00
Data updated for time: 2025-03-05 04:00:00
Data updated for time: 2025-03-05 05:00:00
Data updated for time: 2025-03-05 05:00:00
Data updated for time: 2025-03-05 06:00:00
Data updated for time: 2025-03-05 06:00:00
Data updated for time: 2025-03-05 07:00:00
Data updated for time: 2025-03-05 07:00:00
Data updated for time: 2025-03-05 08:00:00
Data updated for time: 2025-03-05 08:00:00
Data updated for time: 2025-03-05 09:00:00
Data updated for time: 2025-03-05 09:00:00
Data updated for time: 2025-03-05 10:00:00
Data updated for time: 2025-03-05 10:00:00
Data updated for time: 2025-03-05 11:00:00
Data updated for time: 2025-03-05 11:00:00
Data updated for time: 2025-03-05 12:00:00
Data updated for time: 2025-03-05 12:00:00
Data updated for time: 2025-03-05 13:00:00
Data updated for time: 2025-03-05 13:00:00
Data updated for time: 2025-03-05 14:00:00
Data updated for time: 2025-03-05 14:00:00
Data updated for time: 2025-03-05 15:00:00
Data updated for time: 2025-03-05 15:00:00
Data updated for time: 2025-03-05 16:00:00
Data updated for time: 2025-03-05 16:00:00
Data updated for time: 2025-03-05 17:00:00
Data updated for time: 2025-03-05 17:00:00
Data updated for time: 2025-03-05 18:00:00
Data updated for time: 2025-03-05 18:00:00
Data updated for time: 2025-03-05 19:00:00
Data updated for time: 2025-03-05 19:00:00
Data updated for time: 2025-03-05 20:00:00
Data updated for time: 2025-03-05 20:00:00
Data updated for time: 2025-03-05 21:00:00
Data updated for time: 2025-03-05 21:00:00
Data updated for time: 2025-03-05 22:00:00
Data updated for time: 2025-03-05 22:00:00
Data updated for time: 2025-03-05 23:00:00
Data updated for time: 2025-03-05 23:00:00
Data updated for time: 2025-03-06 00:00:00
Data updated for time: 2025-03-06 00:00:00
Data updated for time: 2025-03-06 01:00:00
Data updated for time: 2025-03-06 01:00:00
Data updated for time: 2025-03-06 02:00:00
Data updated for time: 2025-03-06 02:00:00
Data updated for time: 2025-03-06 03:00:00
Data updated for time: 2025-03-06 03:00:00
Data updated for time: 2025-03-06 04:00:00
Data updated for time: 2025-03-06 04:00:00
Data updated for time: 2025-03-06 05:00:00
Data updated for time: 2025-03-06 05:00:00
Data updated for time: 2025-03-06 06:00:00
Data updated for time: 2025-03-06 06:00:00
Data updated for time: 2025-03-06 07:00:00
Data updated for time: 2025-03-06 07:00:00
Data updated for time: 2025-03-06 08:00:00
Data updated for time: 2025-03-06 08:00:00
Data updated for time: 2025-03-06 09:00:00
Data updated for time: 2025-03-06 09:00:00
Data updated for time: 2025-03-06 10:00:00
Data updated for time: 2025-03-06 10:00:00
Data updated for time: 2025-03-06 11:00:00
Data updated for time: 2025-03-06 11:00:00
Data updated for time: 2025-03-06 12:00:00
Data updated for time: 2025-03-06 12:00:00
Data updated for time: 2025-03-06 13:00:00
Data updated for time: 2025-03-06 13:00:00
Data updated for time: 2025-03-06 14:00:00
Data updated for time: 2025-03-06 14:00:00
Data updated for time: 2025-03-06 15:00:00
Data updated for time: 2025-03-06 15:00:00
Data updated for time: 2025-03-06 16:00:00
Data updated for time: 2025-03-06 16:00:00
Data updated for time: 2025-03-06 17:00:00
Data updated for time: 2025-03-06 17:00:00
Data updated for time: 2025-03-06 18:00:00
Data updated for time: 2025-03-06 18:00:00
Data updated for time: 2025-03-06 19:00:00
Data updated for time: 2025-03-06 19:00:00
Data updated for time: 2025-03-06 20:00:00
Data updated for time: 2025-03-06 20:00:00
Data updated for time: 2025-03-06 21:00:00
Data updated for time: 2025-03-06 21:00:00
Data updated for time: 2025-03-06 22:00:00
Data updated for time: 2025-03-06 22:00:00
Data updated for time: 2025-03-06 23:00:00
Data updated for time: 2025-03-06 23:00:00
Data updated for time: 2025-03-07 00:00:00
Data updated for time: 2025-03-07 00:00:00
Data updated for time: 2025-03-07 01:00:00
Data updated for time: 2025-03-07 01:00:00
Data updated for time: 2025-03-07 02:00:00
Data updated for time: 2025-03-07 02:00:00
Data updated for time: 2025-03-07 03:00:00
Data updated for time: 2025-03-07 03:00:00
Data updated for time: 2025-03-07 04:00:00
Data updated for time: 2025-03-07 04:00:00
Data updated for time: 2025-03-07 05:00:00
Data updated for time: 2025-03-07 05:00:00
Data updated for time: 2025-03-07 06:00:00
Data updated for time: 2025-03-07 06:00:00
Data updated for time: 2025-03-07 07:00:00
Data updated for time: 2025-03-07 07:00:00
Data updated for time: 2025-03-07 08:00:00
Data updated for time: 2025-03-07 08:00:00
Data updated for time: 2025-03-07 09:00:00
Data updated for time: 2025-03-07 09:00:00
Data updated for time: 2025-03-07 10:00:00
Data updated for time: 2025-03-07 10:00:00
Data updated for time: 2025-03-07 11:00:00
Data updated for time: 2025-03-07 11:00:00
Data updated for time: 2025-03-07 12:00:00
Data updated for time: 2025-03-07 12:00:00
Data updated for time: 2025-03-07 13:00:00
Data updated for time: 2025-03-07 13:00:00
Data updated for time: 2025-03-07 14:00:00
Data updated for time: 2025-03-07 14:00:00
Data updated for time: 2025-03-07 15:00:00
Data updated for time: 2025-03-07 15:00:00
Data updated for time: 2025-03-07 16:00:00
Data updated for time: 2025-03-07 16:00:00
Data updated for time: 2025-03-07 17:00:00
Data updated for time: 2025-03-07 17:00:00
Data updated for time: 2025-03-07 18:00:00
Data updated for time: 2025-03-07 18:00:00
Data updated for time: 2025-03-07 19:00:00
Data updated for time: 2025-03-07 19:00:00
Data updated for time: 2025-03-07 20:00:00
Data updated for time: 2025-03-07 20:00:00
Data updated for time: 2025-03-07 21:00:00
Data updated for time: 2025-03-07 21:00:00
Data updated for time: 2025-03-07 22:00:00
Data updated for time: 2025-03-07 22:00:00
Data updated for time: 2025-03-07 23:00:00
Data updated for time: 2025-03-07 23:00:00
Data updated for time: 2025-03-08 00:00:00
Data updated for time: 2025-03-08 00:00:00
Data updated for time: 2025-03-08 01:00:00
Data updated for time: 2025-03-08 01:00:00
Data updated for time: 2025-03-08 02:00:00
Data updated for time: 2025-03-08 02:00:00
Data updated for time: 2025-03-08 03:00:00
Data updated for time: 2025-03-08 03:00:00
Data updated for time: 2025-03-08 04:00:00
Data updated for time: 2025-03-08 04:00:00
Data updated for time: 2025-03-08 05:00:00
Data updated for time: 2025-03-08 05:00:00
Data updated for time: 2025-03-08 06:00:00
Data updated for time: 2025-03-08 06:00:00
Data updated for time: 2025-03-08 07:00:00
Data updated for time: 2025-03-08 07:00:00
Data updated for time: 2025-03-08 08:00:00
Data updated for time: 2025-03-08 08:00:00
Data updated for time: 2025-03-08 09:00:00
Data updated for time: 2025-03-08 09:00:00
Data updated for time: 2025-03-08 10:00:00
Data updated for time: 2025-03-08 10:00:00
Data updated for time: 2025-03-08 11:00:00
Data updated for time: 2025-03-08 11:00:00
Data updated for time: 2025-03-08 12:00:00
Data updated for time: 2025-03-08 12:00:00
Data updated for time: 2025-03-08 13:00:00
Data updated for time: 2025-03-08 13:00:00
Data updated for time: 2025-03-08 14:00:00
Data updated for time: 2025-03-08 14:00:00
Data updated for time: 2025-03-08 15:00:00
Data updated for time: 2025-03-08 15:00:00
Data updated for time: 2025-03-08 16:00:00
Data updated for time: 2025-03-08 16:00:00
Data updated for time: 2025-03-08 17:00:00
Data updated for time: 2025-03-08 17:00:00
Data updated for time: 2025-03-08 18:00:00
Data updated for time: 2025-03-08 18:00:00
Data updated for time: 2025-03-08 19:00:00
Data updated for time: 2025-03-08 19:00:00
Data updated for time: 2025-03-08 20:00:00
Data updated for time: 2025-03-08 20:00:00
Data updated for time: 2025-03-08 21:00:00
Data updated for time: 2025-03-08 21:00:00
Data updated for time: 2025-03-08 22:00:00
Data updated for time: 2025-03-08 22:00:00
Data updated for time: 2025-03-08 23:00:00
Data updated for time: 2025-03-08 23:00:00
Data updated for time: 2025-03-09 00:00:00
Data updated for time: 2025-03-09 00:00:00
Data updated for time: 2025-03-09 01:00:00
Data updated for time: 2025-03-09 01:00:00
Data updated for time: 2025-03-09 02:00:00
Data updated for time: 2025-03-09 02:00:00
Data updated for time: 2025-03-09 03:00:00
Data updated for time: 2025-03-09 03:00:00
Data updated for time: 2025-03-09 04:00:00
Data updated for time: 2025-03-09 04:00:00
Data updated for time: 2025-03-09 05:00:00
Data updated for time: 2025-03-09 05:00:00
Data updated for time: 2025-03-09 06:00:00
Data updated for time: 2025-03-09 06:00:00
Data updated for time: 2025-03-09 07:00:00
Data updated for time: 2025-03-09 07:00:00
Data updated for time: 2025-03-09 08:00:00
Data updated for time: 2025-03-09 08:00:00
Data updated for time: 2025-03-09 09:00:00
Data updated for time: 2025-03-09 09:00:00
Data updated for time: 2025-03-09 10:00:00
Data updated for time: 2025-03-09 10:00:00
Data updated for time: 2025-03-09 11:00:00
Data updated for time: 2025-03-09 11:00:00
Data updated for time: 2025-03-09 12:00:00
Data updated for time: 2025-03-09 12:00:00
Data updated for time: 2025-03-09 13:00:00
Data updated for time: 2025-03-09 13:00:00
Data updated for time: 2025-03-09 14:00:00
Data updated for time: 2025-03-09 14:00:00
Data updated for time: 2025-03-09 15:00:00
Data updated for time: 2025-03-09 15:00:00
Data updated for time: 2025-03-09 16:00:00
Data updated for time: 2025-03-09 16:00:00
Data updated for time: 2025-03-09 17:00:00
Data updated for time: 2025-03-09 17:00:00
Data updated for time: 2025-03-09 18:00:00
Data updated for time: 2025-03-09 18:00:00
Data updated for time: 2025-03-09 19:00:00
Data updated for time: 2025-03-09 19:00:00
Data updated for time: 2025-03-09 20:00:00
Data updated for time: 2025-03-09 20:00:00
Data updated for time: 2025-03-09 21:00:00
Data updated for time: 2025-03-09 21:00:00
Data updated for time: 2025-03-09 22:00:00
Data updated for time: 2025-03-09 22:00:00
Data updated for time: 2025-03-09 23:00:00
Data updated for time: 2025-03-09 23:00:00
Data updated for time: 2025-03-10 00:00:00
Data updated for time: 2025-03-10 00:00:00
Data updated for time: 2025-03-10 01:00:00
Data updated for time: 2025-03-10 01:00:00
Data updated for time: 2025-03-10 02:00:00
Data updated for time: 2025-03-10 02:00:00
Data updated for time: 2025-03-10 03:00:00
Data updated for time: 2025-03-10 03:00:00
Data updated for time: 2025-03-10 04:00:00
Data updated for time: 2025-03-10 04:00:00
Data updated for time: 2025-03-10 05:00:00
Data updated for time: 2025-03-10 05:00:00
Data updated for time: 2025-03-10 06:00:00
Data updated for time: 2025-03-10 06:00:00
Data updated for time: 2025-03-10 07:00:00
Data updated for time: 2025-03-10 07:00:00
Data updated for time: 2025-03-10 08:00:00
Data updated for time: 2025-03-10 08:00:00
Data updated for time: 2025-03-10 09:00:00
Data updated for time: 2025-03-10 09:00:00
Data updated for time: 2025-03-10 10:00:00
Data updated for time: 2025-03-10 10:00:00
Data updated for time: 2025-03-10 11:00:00
Data updated for time: 2025-03-10 11:00:00
Data updated for time: 2025-03-10 12:00:00
Data updated for time: 2025-03-10 12:00:00
Data updated for time: 2025-03-10 13:00:00
Data updated for time: 2025-03-10 13:00:00
Data updated for time: 2025-03-10 14:00:00
Data updated for time: 2025-03-10 14:00:00
Data updated for time: 2025-03-10 15:00:00
Data updated for time: 2025-03-10 15:00:00
Data updated for time: 2025-03-10 16:00:00
Data updated for time: 2025-03-10 16:00:00
Data updated for time: 2025-03-10 17:00:00
Data updated for time: 2025-03-10 17:00:00
Data updated for time: 2025-03-10 18:00:00
Data updated for time: 2025-03-10 18:00:00
Data updated for time: 2025-03-10 19:00:00
Data updated for time: 2025-03-10 19:00:00
Data updated for time: 2025-03-10 20:00:00
Data updated for time: 2025-03-10 20:00:00
Data updated for time: 2025-03-10 21:00:00
Data updated for time: 2025-03-10 21:00:00
Data updated for time: 2025-03-10 22:00:00
Data updated for time: 2025-03-10 22:00:00
Data updated for time: 2025-03-10 23:00:00
Data updated for time: 2025-03-10 23:00:00
Data updated for time: 2025-03-11 00:00:00
Data updated for time: 2025-03-11 00:00:00
Data updated for time: 2025-03-11 01:00:00
Data updated for time: 2025-03-11 01:00:00
Data updated for time: 2025-03-11 02:00:00
Data updated for time: 2025-03-11 02:00:00
Data updated for time: 2025-03-11 03:00:00
Data updated for time: 2025-03-11 03:00:00
Data updated for time: 2025-03-11 04:00:00
Data updated for time: 2025-03-11 04:00:00
Data updated for time: 2025-03-11 05:00:00
Data updated for time: 2025-03-11 05:00:00
Data updated for time: 2025-03-11 06:00:00
Data updated for time: 2025-03-11 06:00:00
Data updated for time: 2025-03-11 07:00:00
Data updated for time: 2025-03-11 07:00:00
Data updated for time: 2025-03-11 08:00:00
Data updated for time: 2025-03-11 08:00:00
Data updated for time: 2025-03-11 09:00:00
Data updated for time: 2025-03-11 09:00:00
Data updated for time: 2025-03-11 10:00:00
Data updated for time: 2025-03-11 10:00:00
Data updated for time: 2025-03-11 11:00:00
Data updated for time: 2025-03-11 11:00:00
Data updated for time: 2025-03-11 12:00:00
Data updated for time: 2025-03-11 12:00:00
Data updated for time: 2025-03-11 13:00:00
Data updated for time: 2025-03-11 13:00:00
Data updated for time: 2025-03-11 14:00:00
Data updated for time: 2025-03-11 14:00:00
Data saved for time: 2025-03-11 15:00:00
Data updated for time: 2025-03-11 15:00:00
Data saved for time: 2025-03-11 16:00:00
Data updated for time: 2025-03-11 16:00:00
Data saved for time: 2025-03-11 17:00:00
Data updated for time: 2025-03-11 17:00:00
Data saved for time: 2025-03-11 18:00:00
Data updated for time: 2025-03-11 18:00:00
Data saved for time: 2025-03-11 19:00:00
Data updated for time: 2025-03-11 19:00:00
Data saved for time: 2025-03-11 20:00:00
Data updated for time: 2025-03-11 20:00:00
Data saved for time: 2025-03-11 21:00:00
Data updated for time: 2025-03-11 21:00:00
Data saved for time: 2025-03-11 22:00:00
Data updated for time: 2025-03-11 22:00:00
Data saved for time: 2025-03-11 23:00:00
Data updated for time: 2025-03-11 23:00:00
Data saved for time: 2025-03-12 00:00:00
Data updated for time: 2025-03-12 00:00:00
Data saved for time: 2025-03-12 01:00:00
Data updated for time: 2025-03-12 01:00:00
Data saved for time: 2025-03-12 02:00:00
Data updated for time: 2025-03-12 02:00:00
Data saved for time: 2025-03-12 03:00:00
Data updated for time: 2025-03-12 03:00:00
Data saved for time: 2025-03-12 04:00:00
Data updated for time: 2025-03-12 04:00:00
Data saved for time: 2025-03-12 05:00:00
Data updated for time: 2025-03-12 05:00:00
Data saved for time: 2025-03-12 06:00:00
Data updated for time: 2025-03-12 06:00:00
Data saved for time: 2025-03-12 07:00:00
Data updated for time: 2025-03-12 07:00:00
Data saved for time: 2025-03-12 08:00:00
Data updated for time: 2025-03-12 08:00:00
Data saved for time: 2025-03-12 09:00:00
Data updated for time: 2025-03-12 09:00:00
Data saved for time: 2025-03-12 10:00:00
Data updated for time: 2025-03-12 10:00:00
Data saved for time: 2025-03-12 11:00:00
Data updated for time: 2025-03-12 11:00:00
Analysis completed
                   time     open     high      low    close      volume  \
190 2025-03-12 02:00:00  1920.61  1921.41  1887.42  1895.89  24313.3933
191 2025-03-12 03:00:00  1895.90  1898.60  1867.09  1868.90  27489.2193
192 2025-03-12 04:00:00  1868.89  1868.90  1852.30  1866.80  23820.9856
193 2025-03-12 05:00:00  1866.79  1880.82  1861.87  1878.53  15840.7181
194 2025-03-12 06:00:00  1878.53  1879.08  1853.12  1873.11  18481.2294
195 2025-03-12 07:00:00  1873.11  1916.66  1872.07  1911.26  52422.4788
196 2025-03-12 08:00:00  1911.26  1935.90  1871.11  1928.10  67585.9061
197 2025-03-12 09:00:00  1928.10  1960.00  1877.67  1894.10  97355.1544
198 2025-03-12 10:00:00  1894.09  1902.00  1883.70  1900.33  29777.0658
199 2025-03-12 11:00:00  1900.34  1915.52  1900.34  1909.99   9373.5371

     support  resistance  macd  macd_signal  ...  engulfing  \
190      NaN         NaN   NaN          NaN  ...         no
191      NaN         NaN   NaN          NaN  ...         no
192      NaN         NaN   NaN          NaN  ...         no
193      NaN         NaN   NaN          NaN  ...    bullish
194      NaN         NaN   NaN          NaN  ...         no
195      NaN         NaN   NaN          NaN  ...         no
196      NaN         NaN   NaN          NaN  ...         no
197      NaN         NaN   NaN          NaN  ...         no
198      NaN         NaN   NaN          NaN  ...         no
199      NaN         NaN   NaN          NaN  ...         no

                    reversal  doji  macd_trade  rsi_trade  stochastic_trade  \
190                       no    no        wait       wait              wait
191                       no    no        wait       wait              wait
192  bullish_inverted_hammer    no        wait       wait              wait
193                       no    no        wait       wait              wait
194  bullish_inverted_hammer    no        wait       wait              wait
195                       no    no        wait       wait              wait
196           bullish_hammer    no        wait       wait              wait
197                       no    no        wait       wait              wait
198                       no    no        wait       wait              wait
199                       no    no        wait       wait              wait

     channel_trade  near_bb_support  near_bb_resistance trade
190           wait              NaN                 NaN  wait
191           wait          1867.09                 NaN  wait
192           wait          1852.30                 NaN  wait
193           wait          1861.87                 NaN  wait
194           wait          1853.12                 NaN  wait
195           wait              NaN                 NaN  wait
196           wait              NaN                 NaN  wait

In [38]:
lookback_slider.value

200

In [39]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import mplfinance as mpf
import ta
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from datetime import datetime

# Date selection widgets
from_date = widgets.DatePicker(
    description='From',
    disabled=False
)
to_date = widgets.DatePicker(
    description='To',
    disabled=False
)

# Window size widget
window_size_input = widgets.IntText(
    value=200,
    description='Window Size:',
    disabled=False
)

# Submit button
submit_button = widgets.Button(
    description='Submit',
    disabled=False,
    button_style='',
    tooltip='Click to submit',
    icon='check'
)

# Display the widgets
display(from_date, to_date, window_size_input, submit_button)

# Database credentials
db_config = {
    'host': 'localhost',
    'user': 'root',
    'password': 'Tamir4578',
    'database': 'portalblog_dev'
}

table_name = 'analyzed_data'
timestamp_col = 'time'
open_col = 'open'
high_col = 'high'
low_col = 'low'
close_col = 'close'

# Create database connection string
db_connection_str = 'mysql+pymysql://{user}:{password}@{host}/{database}'.format(**db_config)
db_connection = create_engine(db_connection_str)

def fetch_data_from_db(window_size=200, start_date=None, end_date=None):
    query = f'SELECT * FROM (SELECT * FROM {table_name} ORDER BY {timestamp_col} DESC LIMIT {window_size}) AS recent_data'
    if start_date and end_date:
        query = f'SELECT * FROM (SELECT * FROM {table_name} WHERE {timestamp_col} BETWEEN "{start_date}" AND "{end_date}" ORDER BY {timestamp_col} DESC LIMIT {window_size}) AS recent_data'
    query += f' ORDER BY {timestamp_col} ASC'
    df = pd.read_sql(query, db_connection)
    # Convert the 'time' column to datetime
    df['time'] = pd.to_datetime(df['time'])

    # Set the 'time' column as the index
    df.set_index('time', inplace=True)
    return df

def on_submit_button_clicked(b):
    start_date = from_date.value.strftime('%Y-%m-%d') if from_date.value else None
    end_date = to_date.value.strftime('%Y-%m-%d') if to_date.value else None
    window_size = window_size_input.value
    global df
    df = fetch_data_from_db(window_size=window_size, start_date=start_date, end_date=end_date)
    # display(df.head())

submit_button.on_click(on_submit_button_clicked)

DatePicker(value=None, description='From', step=1)

DatePicker(value=None, description='To', step=1)

IntText(value=200, description='Window Size:')

Button(description='Submit', icon='check', style=ButtonStyle(), tooltip='Click to submit')

In [40]:
df.tail()

,id,open,high,low,close,volume,resistance,support,macd,macd_signal,...,stochastic_trade,channel_trade,bb_upper,bb_middle,bb_lower,bb_trend,bb_signal,near_bb_support,near_bb_resistance,trade
time,,,,,,,,,,,,,,,,,,,,,
2025-03-11 19:00:00,550,1953.13,1963.00,1942.88,1951.91,24152.60,None,None,None,None,...,wait,wait,1963.57,1895.10,1826.64,sideways,wait,NaN,1963.00,wait
2025-03-11 20:00:00,551,1951.90,1955.42,1936.09,1936.70,15209.90,None,None,None,None,...,wait,wait,1960.46,1901.24,1842.02,sideways,wait,NaN,1955.42,wait
2025-03-11 21:00:00,552,1936.71,1950.61,1936.50,1940.40,9106.88,None,None,None,None,...,wait,wait,1963.45,1905.33,1847.20,sideways,wait,NaN,NaN,wait
2025-03-11 22:00:00,553,1940.40,1952.54,1936.99,1943.70,10323.80,None,None,None,None,...,wait,wait,1965.88,1909.53,1853.18,sideways,wait,NaN,NaN,wait
2025-03-11 23:00:00,554,1943.69,1944.45,1917.17,1923.43,14747.70,None,None,None,None,...,wait,wait,1962.28,1913.21,1864.14,sideways,wait,NaN,NaN,wait

In [41]:
# Set the 'time' column as the index
df.set_index('time', inplace=True)

KeyError: "None of ['time'] are in the columns"

In [42]:
import plotly.graph_objects as go
def find_extremum(df, backcandles=500, candle_group=10):
    if df.index.name == 'time':
        df = df.reset_index().set_index('id')  # Reset index and set 'id' as the index
    candleid = len(df) - 1
    print("candle_id ", candleid)
    maxim = np.array([])
    minim = np.array([])
    xxmin = np.array([])
    xxmax = np.array([])

    for i in range(candleid - backcandles, candleid + 1, candle_group):
        minim = np.append(minim, df.low.iloc[i:i + candle_group].min())
        xxmin = np.append(xxmin, df.low.iloc[i:i + candle_group].idxmin())
    for i in range(candleid - backcandles, candleid + 1, candle_group):
        maxim = np.append(maxim, df.high.iloc[i:i + candle_group].max())
        xxmax = np.append(xxmax, df.high.iloc[i:i + candle_group].idxmax())
    slmin, intercmin = np.polyfit(xxmin, minim, 1)
    slmax, intercmax = np.polyfit(xxmax, maxim, 1)
    adjintercmin = df.low.iloc[candleid-backcandles:candleid].min() - slmin*df.low.iloc[candleid-backcandles:candleid].idxmin()
    adjintercmax = df.high.iloc[candleid-backcandles:candleid].max() - slmax*df.high.iloc[candleid-backcandles:candleid].idxmax()
    miny=slmin*xxmin + adjintercmin
    maxy=slmax*xxmax + adjintercmax
    return intercmin, intercmax,minim, maxim, xxmin, xxmax, slmin, slmax, adjintercmin, adjintercmax, miny, maxy

# ====== calculate support and resistance levels ======
intercmin, intercmax, minim, maxim, xxmin, xxmax, slmin, slmax, adjintercmin, adjintercmax, miny, maxy = find_extremum(df, 30, 5)
print("Slope max",slmax)
support_y=slmin*xxmin + adjintercmin
resistance_y=slmax*xxmax + adjintercmax
# dfpl = df[1:len(df)-1]
# intercmax = maxim.max() + intercmax
dfpl = df
fig = go.Figure(data=[go.Candlestick(x=dfpl.id,
                open=dfpl['open'],
                high=dfpl['high'],
                low=dfpl['low'],
                close=dfpl['close'])])
fig.add_trace(go.Scatter(x=xxmin, y=slmin*xxmin + adjintercmin, mode='lines', name='min slope'))
fig.add_trace(go.Scatter(x=xxmax, y=slmax*xxmax + adjintercmax, mode='lines', name='max slope'))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.id, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))

fig.show()

candle_id  47
Slope max -0.2588226431338753

In [43]:
# ====== calculate support and resistance levels continiously ======
x_values = xxmin.astype(int)
for x in range(x_values[0], df.id.max() + 1):
    df.loc[df.id == x, 'support'] = slmin * x + adjintercmin
    df.loc[df.id == x, 'resistance'] = slmax * x + adjintercmax

In [44]:
df.tail(2)

,id,open,high,low,close,volume,resistance,support,macd,macd_signal,...,stochastic_trade,channel_trade,bb_upper,bb_middle,bb_lower,bb_trend,bb_signal,near_bb_support,near_bb_resistance,trade
time,,,,,,,,,,,,,,,,,,,,,
2025-03-11 22:00:00,553,1940.40,1952.54,1936.99,1943.70,10323.8,2001.214143,1859.731621,None,None,...,wait,wait,1965.88,1909.53,1853.18,sideways,wait,NaN,NaN,wait
2025-03-11 23:00:00,554,1943.69,1944.45,1917.17,1923.43,14747.7,2000.955321,1864.524876,None,None,...,wait,wait,1962.28,1913.21,1864.14,sideways,wait,NaN,NaN,wait

In [162]:
# Set the 'time' column as the index
df.set_index('time', inplace=True)

In [46]:
df.reset_index(inplace=True)
# df.set_index('id', inplace=True)

In [47]:
# Hadgalah
for index, row in df.iterrows():
    print(index)
    update_db(row)

0
Data updated for time: 2025-03-10 00:00:00
1
Data updated for time: 2025-03-10 01:00:00
2
Data updated for time: 2025-03-10 02:00:00
3
Data updated for time: 2025-03-10 03:00:00
4
Data updated for time: 2025-03-10 04:00:00
5
Data updated for time: 2025-03-10 05:00:00
6
Data updated for time: 2025-03-10 06:00:00
7
Data updated for time: 2025-03-10 07:00:00
8
Data updated for time: 2025-03-10 08:00:00
9
Data updated for time: 2025-03-10 09:00:00
10
Data updated for time: 2025-03-10 10:00:00
11
Data updated for time: 2025-03-10 11:00:00
12
Data updated for time: 2025-03-10 12:00:00
13
Data updated for time: 2025-03-10 13:00:00
14
Data updated for time: 2025-03-10 14:00:00
15
Data updated for time: 2025-03-10 15:00:00
16
Data updated for time: 2025-03-10 16:00:00
17
Data updated for time: 2025-03-10 17:00:00
18
Data updated for time: 2025-03-10 18:00:00
19
Data updated for time: 2025-03-10 19:00:00
20
Data updated for time: 2025-03-10 20:00:00
21
Data updated for time: 2025-03-10 21:00:00
22
Data updated for time: 2025-03-10 22:00:00
23
Data updated for time: 2025-03-10 23:00:00
24
Data updated for time: 2025-03-11 00:00:00
25
Data updated for time: 2025-03-11 01:00:00
26
Data updated for time: 2025-03-11 02:00:00
27
Data updated for time: 2025-03-11 03:00:00
28
Data updated for time: 2025-03-11 04:00:00
29
Data updated for time: 2025-03-11 05:00:00
30
Data updated for time: 2025-03-11 06:00:00
31
Data updated for time: 2025-03-11 07:00:00
32
Data updated for time: 2025-03-11 08:00:00
33
Data updated for time: 2025-03-11 09:00:00
34
Data updated for time: 2025-03-11 10:00:00
35
Data updated for time: 2025-03-11 11:00:00
36
Data updated for time: 2025-03-11 12:00:00
37
Data updated for time: 2025-03-11 13:00:00
38
Data updated for time: 2025-03-11 14:00:00
39
Data updated for time: 2025-03-11 15:00:00
40
Data updated for time: 2025-03-11 16:00:00
41
Data updated for time: 2025-03-11 17:00:00
42
Data updated for time: 2025-03-11 18:00:00
43
Data updated for time: 2025-03-11 19:00:00
44
Data updated for time: 2025-03-11 20:00:00
45
Data updated for time: 2025-03-11 21:00:00
46
Data updated for time: 2025-03-11 22:00:00
47
Data updated for time: 2025-03-11 23:00:00

SUPPORT & RESISTANCE hadgalsanaas hoish db-nees data tataj chart zurj shalgah heseg

In [48]:
# ==== db-nees data tataj chart zurah =====
df = fetch_data_from_db(window_size=200, start_date=None, end_date=None)

# Plot candlestick chart with support, resistance, and Bollinger Bands
fig = go.Figure(data=[go.Candlestick(x=df.index,
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'])])
fig.add_trace(go.Scatter(x=df.index, y=df['support'], mode='lines', name='Support', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['resistance'], mode='lines', name='Resistance', line=dict(color='red')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))

fig.update_layout(
    xaxis=dict(
        title="Time"
    ),
    yaxis=dict(
        title="Price"
    )
)

fig.show()

# Plot RSI chart separately
rsi_fig = go.Figure()
rsi_fig.add_trace(go.Scatter(x=df.index, y=df['rsi'], mode='lines', name='RSI', line=dict(color='purple')))

# Add RSI level lines
rsi_levels = [30, 50, 70]
for level in rsi_levels:
    rsi_fig.add_trace(go.Scatter(x=[df.index[0], df.index[-1]], y=[level, level], mode='lines', name=f'RSI {level}', line=dict(color='grey', dash='dash')))

# Update layout for RSI chart
rsi_fig.update_layout(
    yaxis=dict(
        title="RSI",
        range=[0, 100]
    ),
    xaxis=dict(
        title="Time"
    ),
    annotations=[
        dict(
            x=1.01,
            y=level,
            xref='paper',
            yref='y',
            text=f'RSI {level}',
            showarrow=False,
            font=dict(color='grey')
        ) for level in rsi_levels
    ]
)

rsi_fig.show()

In [49]:
# ========= trade analyze =========
df = fetch_data_from_db(window_size=50, start_date=None, end_date=None)

# analyze with rsi and support and resistance and bollinger bands
price_range = 25
df['trade'] = 'wait'
df['trade'] = df.apply(lambda row: 'buy' if (row['close'] <= (row['support'] + 10) and row['close'] >= (row['support'] - 10) and pd.notnull(row['near_resistance']) and row['rsi'] < 35) else row['trade'], axis=1)
df['trade'] = df.apply(lambda row: 'sell' if (row['close'] <= (row['resistance'] + 10) and row['close'] >= (row['resistance'] - 10) and pd.notnull(row['near_bb_resistance']) and row['rsi'] > 65) else row['trade'], axis=1)
# df['near_resistance'] = df.apply(lambda row: row['high'] if (abs(row['resistance'] - row['high'])) <= price_range and abs(row['bb_upper'] - row['high']) <= price_range else row['near_resistance'], axis=1)
df['near_resistance'] = df.apply(lambda row: row['high'] if (abs(row['resistance'] - row['high'])) <= price_range and abs(row['bb_upper'] - row['high']) <= price_range and pd.notnull(row['near_bb_resistance'] and row['rsi'] > 70) else row['near_resistance'], axis=1)
df['near_support'] = df.apply(lambda row: row['low'] if (abs(row['support'] - row['low'])) <= price_range and abs(row['bb_lower'] - row['low']) <= price_range and pd.notnull(row['near_bb_support'] and row['rsi'] < 30) else row['near_support'], axis=1)
# Plot candlestick chart with support, resistance, and Bollinger Bands
fig = go.Figure(data=[go.Candlestick(x=df.index,
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'])])
fig.add_trace(go.Scatter(x=df.index, y=df['support'], mode='lines', name='Support', line=dict(color='green')))
fig.add_trace(go.Scatter(x=df.index, y=df['resistance'], mode='lines', name='Resistance', line=dict(color='red')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_upper'], mode='lines', name='BB Upper', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_middle'], mode='lines', name='BB Middle', line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df.index, y=df['bb_lower'], mode='lines', name='BB Lower', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=df.index, y=df['near_support'], mode='markers', name='Near Support', marker=dict(symbol='star', color='red', size=10)))
fig.add_trace(go.Scatter(x=df.index, y=df['near_resistance'], mode='markers', name='Near Resistance', marker=dict(symbol='star',color='green', size=20)))
# fig.add_trace(go.Scatter(x=df.index, y=df['near_bb_support'], mode='markers', name='Near BB Support', marker=dict(symbol='star', color='blue', size=10)))
# fig.add_trace(go.Scatter(x=df.index, y=df['near_bb_resistance'], mode='markers', name='Near BB Resistance', marker=dict(color='red', size=10)))
fig.show()

In [164]:
df.reset_index(inplace=True)
# Hadgalah
for index, row in df.iterrows():
    print(index)
    update_db(row)

0
Data updated for time: 2025-03-07 05:00:00
1
Data updated for time: 2025-03-07 06:00:00
2
Data updated for time: 2025-03-07 07:00:00
3
Data updated for time: 2025-03-07 08:00:00
4
Data updated for time: 2025-03-07 09:00:00
5
Data updated for time: 2025-03-07 10:00:00
6
Data updated for time: 2025-03-07 11:00:00
7
Data updated for time: 2025-03-07 12:00:00
8
Data updated for time: 2025-03-07 13:00:00
9
Data updated for time: 2025-03-07 14:00:00
10
Data updated for time: 2025-03-07 15:00:00
11
Data updated for time: 2025-03-07 16:00:00
12
Data updated for time: 2025-03-07 17:00:00
13
Data updated for time: 2025-03-07 18:00:00
14
Data updated for time: 2025-03-07 19:00:00
15
Data updated for time: 2025-03-07 20:00:00
16
Data updated for time: 2025-03-07 21:00:00
17
Data updated for time: 2025-03-07 22:00:00
18
Data updated for time: 2025-03-07 23:00:00
19
Data updated for time: 2025-03-08 00:00:00
20
Data updated for time: 2025-03-08 01:00:00
21
Data updated for time: 2025-03-08 02:00:00
22
Data updated for time: 2025-03-08 03:00:00
23
Data updated for time: 2025-03-08 04:00:00
24
Data updated for time: 2025-03-08 05:00:00
25
Data updated for time: 2025-03-08 06:00:00
26
Data updated for time: 2025-03-08 07:00:00
27
Data updated for time: 2025-03-08 08:00:00
28
Data updated for time: 2025-03-08 09:00:00
29
Data updated for time: 2025-03-08 10:00:00
30
Data updated for time: 2025-03-08 11:00:00
31
Data updated for time: 2025-03-08 12:00:00
32
Data updated for time: 2025-03-08 13:00:00
33
Data updated for time: 2025-03-08 14:00:00
34
Data updated for time: 2025-03-08 15:00:00
35
Data updated for time: 2025-03-08 16:00:00
36
Data updated for time: 2025-03-08 17:00:00
37
Data updated for time: 2025-03-08 18:00:00
38
Data updated for time: 2025-03-08 19:00:00
39
Data updated for time: 2025-03-08 20:00:00
40
Data updated for time: 2025-03-08 21:00:00
41
Data updated for time: 2025-03-08 22:00:00
42
Data updated for time: 2025-03-08 23:00:00
43
Data updated for time: 2025-03-09 00:00:00
44
Data updated for time: 2025-03-09 01:00:00
45
Data updated for time: 2025-03-09 02:00:00
46
Data updated for time: 2025-03-09 03:00:00
47
Data updated for time: 2025-03-09 04:00:00
48
Data updated for time: 2025-03-09 05:00:00
49
Data updated for time: 2025-03-09 06:00:00